### ISSUE TITLE
为啥这里的类型定义和 typescript 默认模板的不一致呢

### ISSUE THREAD

**Issue by shynome** [wechat-miniprogram/api-typings#1]
rt

**Comment by SgLy** [comment]
具体是哪些地方不一致？如果是说 wx 接口不一致的话，是因为基础库版本更新导致的

**Comment by SgLy** [comment]
`lib.wx.cloud.d.ts` 是云开发的定义文件，之后会一起放出来；`lib.wa.es6.d.ts` 是 ES6 的定义文件，可以在 [TypeScript 的源](https://github.com/Microsoft/TypeScript) 里找到，在 `tsconfig.json` 里面 `compilerOptions.lib` 加上 `ES6` 也可以的
