### ISSUE TITLE
和@types/node同时使用

### ISSUE THREAD

**Issue by czl032405** [wechat-miniprogram/api-typings#100]
Cannot redeclare block-scoped variable 'console'.

node_modules/@types/node/globals.d.ts:145:13 - error TS2451: Cannot redeclare block-scoped variable 'console'.
145 declare var console: Console;
                ~~~~~~~
node_modules/miniprogram-api-typings/types/wx/lib.wx.api.d.ts:15774:15
15774 declare const console: WechatMiniprogram.Console
                 ~~~~~~~
'console' was also declared here.

**Comment by Mister-Hope** [comment]
Why do you have to use them together?

**Comment by Mister-Hope** [comment]
Advice: if there are deps in your repo using @types/node, then you have to held muti tsconfig.json in your repo. In the miniprogram folder, use compileroptions.types to only include types you need, while the root config remains unmodified.
