### ISSUE TITLE
无法重新声明块范围变量“console”

### ISSUE THREAD

**Issue by q716015** [wechat-miniprogram/api-typings#103]
无法重新声明块范围变量“console”。ts(2451)

lib.dom.d.ts(19661, 13): 'console' was also declared here.

lib.wx.api.d.ts:15775:15 - error TS2451: Cannot redeclare block-scoped variable 'console'.

declare const console: WechatMiniprogram.Console

**Comment by Mister-Hope** [comment]
See #66. Why don't you check the issues before opening a new one

**Comment by SgLy** [comment]
Duplicate of #66 .
