### ISSUE TITLE
缺少 IAppOption 定义

### ISSUE THREAD

**Issue by MapleYin** [wechat-miniprogram/api-typings#104]
在小程序 typescript 初始化app 中有 用到 IAppOption

**Comment by SgLy** [comment]
例子里的 `IAppOption` 是个泛型，定义在 `typings/index.d.ts`，是你在 App 上挂的自定义变量的类型。一般来说你去掉让 ts 自动推导也是可以的，或者你把自定义变量的类型手动指定也行，换个名字也可以的
