### ISSUE TITLE
使用 typescript 时，在组件中无法使用behavior 中定义的方法，编译报错

### ISSUE THREAD

**Issue by link-cathy** [wechat-miniprogram/api-typings#106]

**Comment by SgLy** [comment]
这个目前确实没有太好的办法，behavior 对于类型系统来说本质上只是一个字符串而已，从 behavior 的返回值去逆推 behavior 的定义来做 mixin 有一定难度。而且 behavior 可以做的事情比较多，自动去做也很难做得好。

可以看一下测试用例里对 computed 的 behavior 的手动处理方法：[代码](https://github.com/wechat-miniprogram/api-typings/blob/master/test/computed.test.ts)、[定义](https://github.com/wechat-miniprogram/api-typings/blob/master/test/computed.test.d.ts)
