### ISSUE TITLE
安装了miniprogram-api-typings但是vscode显示找不到wx

### ISSUE THREAD

**Issue by QianDingwei** [wechat-miniprogram/api-typings#107]
![image](https://user-images.githubusercontent.com/47747920/77143238-95094f80-6abd-11ea-8674-518bb4979928.png)

**Comment by SgLy** [comment]
因为这个包不在 `@types` 下，所以 ts 没有自动引用。有两种方案：

一是在你项目的定义文件（例如 `index.d.ts`）里通过 reference 来引入，比如
```ts
/// <reference path="./node_modules/miniprogram-api-typings/index.d.ts" />
```

二是在 `tsconfig.json` 中指定 `compilerOptions.types`，比如：
```json
{
  "compilerOptions": {
    "types": ["miniprogram-api-typings"]
  }
}
```
看起来比上面的方法优雅一点，不过缺点是如果你添加了其他的 `@types/xxx` 定义包，要手动加在这里

**Comment by QianDingwei** [comment]
抱歉，多问一句哈，第一种方法的 index.d.ts是指的哪个文件，是随意新建的一个文件嘛？还是说新建了一个文件后，还需要做什么额外的工作，因为我新建了一个好像并不生效，谢谢

**Comment by SgLy** [comment]
一般项目里会有一些自己的类型定义，就写在某个 `.d.ts` 里？试试 `type.d.ts`，或者看看调整 `tsconfig.json` 里的 `include` 和 `files` 能不能把这个文件编进去

**Comment by QianDingwei** [comment]
通过include进行貌似也不行诶

**Comment by SgLy** [comment]
抱歉，是我误导你了……命名为 `type.d.ts` 应该是会被包含进去的，其他的 `.d.ts` 后缀好像不会被包含，除非用 `files` 去指定。

那个 `<reference>`  不放在 `.d.ts` 文件中，放在项目里随意一个 ts 文件开头也可以 ~~就是有点丑~~

晚一些我在 README 里加一下使用方法吧，这里好像确实有点坑

**Comment by QianDingwei** [comment]
![image](https://user-images.githubusercontent.com/47747920/77167836-bab04c00-6af1-11ea-8de4-fb3c12bef680.png)
我试了一下，好像随意放在一个ts文件开头还是不行

**Comment by QianDingwei** [comment]
我试了一下，好像随意放在一个ts文件开头还是不行。
![image](https://user-images.githubusercontent.com/47747920/77167929-e6cbcd00-6af1-11ea-9baa-d9d017dffb29.png)

**Comment by QianDingwei** [comment]
我试了一下，好像随意放在一个ts文件开头还是不行。
![image](https://user-images.githubusercontent.com/47747920/77168005-0e229a00-6af2-11ea-8d73-c498251cfad7.png)

**Comment by SgLy** [comment]
三个斜杠连在一起，这个是 [三斜杠指令](https://www.typescriptlang.org/docs/handbook/triple-slash-directives.html)

**Comment by QianDingwei** [comment]
谢谢，还有更好的解决办法嘛

**Comment by SgLy** [comment]
暂时没有了，或者考虑手动把定义复制到 `@types` 里，不过也很不优雅就是了。这里我再继续看看有没有更简单更好的办法吧

**Comment by yangmingshan** [comment]
@SgLy 有考虑过将此仓库移至 [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) 下吗？

**Comment by SgLy** [comment]
@yangmingshan 考虑过的，有几个问题，比较重要的是基础库并不算严格按照 semver，patch 也经常有新 api 或者新特性，所以 DefinitelyTyped 的版本管理不太够用；其他的比如这个定义是脚本生成，不一定能满足他们的一些要求；每次更新都需要 pr 人工审核；还有就是之前遇到过的 dtslint 的联合类型判断错误的 issue 之类的问题，所以一直没发到 DefinitelyTyped 下面

**Comment by chenzhutian** [comment]
好贴, 建议这个issue挪到readme
