### ISSUE TITLE
wx.chooseContact 缺少定义

### ISSUE THREAD

**Issue by fudiwei** [wechat-miniprogram/api-typings#110]
如题，见图：

![image](https://user-images.githubusercontent.com/18504146/77618817-eb6d0700-6f71-11ea-86b7-56de6b23b315.png)

**Comment by fudiwei** [comment]
@SgLy 声明文件里少定义一个方法！没 fix 就给 Issue 关了？

**Comment by fudiwei** [comment]
@SgLy 看到新 commit 的了，但奇怪的是为啥没跟 Issue 自动关联呢……

**Comment by SgLy** [comment]
因为刚好下午更新版本，我想着 commit 的时候关掉这里能看到 commit id，就不用额外多说一句看起来好啰嗦，于是直接在 commit 里关了没回复😂 我的我的，sorry
