### ISSUE TITLE
使用miniprogram-api-promise时，如何获取代码提示

### ISSUE THREAD

**Issue by shinjidotme** [wechat-miniprogram/api-typings#114]
对typesscript并不是非常了解，引入miniprogram-api-promise后，在代码中使用wxp时就没有用wx时的提示，wxp的声明文件应该怎么写呢

**Comment by Mister-Hope** [comment]
1. miniprogram-api-promise 是啥
2. wxp 是啥？

**Comment by shinjidotme** [comment]
> 1. miniprogram-api-promise 是啥
> 2. wxp 是啥？

@Mister-Hope 不好意思没描述清楚，miniprogram-api-promise是官方给的promise化小程序API的库，新定义了一个wxp对象，```promisifyAll(wx, wxp)``` 遍历wx方法注册到wxp上了

**Comment by Mister-Hope** [comment]
> > 1. miniprogram-api-promise 是啥
> > 2. wxp 是啥？
> 
> @Mister-Hope 不好意思没描述清楚，miniprogram-api-promise是官方给的promise化小程序API的库，新定义了一个wxp对象，`promisifyAll(wx, wxp)` 遍历wx方法注册到wxp上了

噢噢，我有点印象了，前段更新日志看到了。恐怕1没开源2没详细文档吧。难搞啊，看看 @SgLy 能不能搞吧

**Comment by SgLy** [comment]
基础库 2.10.2 开始已经[原生支持 promise 式调用](https://developers.weixin.qq.com/miniprogram/dev/framework/app-service/api.html#%E5%BC%82%E6%AD%A5-API-%E8%BF%94%E5%9B%9E-Promise)了，定义也[支持](https://github.com/wechat-miniprogram/api-typings/blob/94a01f947ed6e9567672ff955121b640af75d603/CHANGELOG.md#2020-03-18-v2102-1)了，可以试一试

如果为了低版本兼容需要用 miniprogram-api-promise 的话，看看最近有没有时间搞一个吧……

> （其实它[开源](https://github.com/wechat-miniprogram/miniprogram-api-promise)了）

**Comment by Mister-Hope** [comment]
那就好整了QAQ，不过哪个开发者不都可能一下子把基础库提的这么高

**Comment by Mister-Hope** [comment]
我看看，如果没啥问题的话，我可以抽空直接把这库改到ts上去，那样直接就有类型定义文件了。

**Comment by SgLy** [comment]
这里似乎有一个实现？ wechat-miniprogram/miniprogram-api-promise#5

**Comment by pensacola1989** [comment]
> 这里似乎有一个实现？ [wechat-miniprogram/miniprogram-api-promise#5](https://github.com/wechat-miniprogram/miniprogram-api-promise/issues/5)

这个不是啊。。这个只是这个api-promise本身的definations，不是miniprogram-api的promisify d.ts文件

**Comment by SgLy** [comment]
@pensacola1989 抱歉，我没太理解你的意思，你说的「api-promise 本身的 definitions」和「miniprogram-api 的 promisify」分别是指什么？

**Comment by baranwang** [comment]
自己给 wxp 指定类型为 `WechatMiniprogram.Wx` 不就行了

**Comment by Eleven90** [comment]
这两天正好遇到这个问题，折腾一波解决了。

miniprogram-api-typings 版本，2.10.4 官方的定义才添加了 promise 返回类型。

```
"miniprogram-api-typings": "^2.10.4"
```

miniprogram-api-promise 我是这样封装的

```js
import { promisifyAll } from 'miniprogram-api-promise'

/**
 * Promise 化的 wx，为扩展了 Promise 的方法。微信官方未支持 Promise 回调定义的，需要额外增加 Promise<any> 返回类型。
 * 
 * 1.tsconfig.json 中的 compilerOptions/lib 需要增加 es2018.promise，否则，使用 finally 方法时会提示错误。
 */
interface $Wx extends WechatMiniprogram.Wx {
  request(option: WechatMiniprogram.RequestOption): WechatMiniprogram.RequestTask & Promise<any>
}

const $wx = {}

promisifyAll(wx, $wx)

export default <$Wx>$wx
```

顺便，我把小程序工具生成出来的 tsconfig.json 里 typeRoots 也改了一下
```
"typeRoots": [
      "./typings",
      "./node_modules/@types",
      "./node_modules/miniprogram-api-typings"
]
```

把 `/typings/types` 整个目录移除了，否则下一次升级 miniprogram-api-typings 包的时候，还得到手动复制到 `/typings/types` 目录下。

**Comment by Eleven90** [comment]
这两天正好遇到这个问题，折腾一波解决了。

miniprogram-api-typings 版本，2.10.4 官方的定义才添加了 promise 返回类型。如果是更低的版本，得手动给 N 多个 api 扩展 Promise<any>。

```
"miniprogram-api-typings": "^2.10.4"
```

miniprogram-api-promise 我是这样封装的

```js
import { promisifyAll } from 'miniprogram-api-promise'

/**
 * Promise 化的 wx，为扩展了 Promise 的方法。微信官方未支持 Promise 回调定义的，需要额外增加 Promise<any> 返回类型。
 * 
 * 1.tsconfig.json 中的 compilerOptions/lib 需要增加 es2018.promise，否则，使用 finally 方法时会提示错误。
 */
interface $Wx extends WechatMiniprogram.Wx {
  request(option: WechatMiniprogram.RequestOption): WechatMiniprogram.RequestTask & Promise<any>
}

const $wx = {}

promisifyAll(wx, $wx)

export default <$Wx>$wx
```

使用的时候

```js
$wx.clearStorage().then().catch().finally()
```

顺便，我把小程序工具生成出来的 tsconfig.json 里 typeRoots 也改了一下
```
"typeRoots": [
  "./typings",
  "./node_modules/@types",
  "./node_modules/miniprogram-api-typings"
]
```

把 `/typings/types` 整个目录移除了，否则下一次升级 miniprogram-api-typings 包的时候，还得到手动复制到 `/typings/types` 目录下。

**Comment by SgLy** [comment]
这里没有新的问题的话就暂时先关闭了，如果有问题再 reopen 讨论吧
