### ISSUE TITLE
setTimout输出能否为NodeJS.Timeout?

### ISSUE THREAD

**Issue by xmsz** [wechat-miniprogram/api-typings#116]
小程序里的是number，这个会和其他所有type冲突。导致出现错误

所以希望setTimeout的输出为 NodeJS.Timeout  或者 NodeJS.Timeout | number

**Comment by Mister-Hope** [comment]
> 小程序里的是number，这个会和其他所有type冲突。导致出现错误
> 
> 所以希望setTimeout的输出为 NodeJS.Timeout 或者 NodeJS.Timeout | number

这个问题我也遇到过，跟npm包对接的时候

**Comment by xmsz** [comment]
> > 小程序里的是number，这个会和其他所有type冲突。导致出现错误
> > 所以希望setTimeout的输出为 NodeJS.Timeout 或者 NodeJS.Timeout | number
> 
> 这个问题我也遇到过，跟npm包对接的时候

确实很蛋疼，主要还覆盖不了，只能删除这个包里的

**Comment by SgLy** [comment]
emm，理论上来说，小程序不在 node 环境里跑，没有理由返回 `NodeJS.Timeout` 的，这个冲突有实际场景可以看一下吗？

**Comment by xmsz** [comment]
> emm，理论上来说，小程序不在 node 环境里跑，没有理由返回 `NodeJS.Timeout` 的，这个冲突有实际场景可以看一下吗？

我看了一下，确实是number，打扰了。 因为项目里有服务端的代码，所以引入@type/node 导致冲突了。

**Comment by SgLy** [comment]
> 因为项目里有服务端的代码，所以引入@type/node 导致冲突了。

应该是可以通过两份 tsconfig.json 来隔开 `@types/node` 的影响的，能解决吗？

**Comment by xmsz** [comment]
> > 因为项目里有服务端的代码，所以引入@type/node 导致冲突了。
> 
> 应该是可以通过两份 tsconfig.json 来隔开 `@types/node` 的影响的，能解决吗？

这样处理是可以，我这里之前偷懒了，觉得两份内容都几乎一样就没有区分
