### ISSUE TITLE
typescript和promise配套使用报错'Promise' only refers to a type

### ISSUE THREAD

**Issue by Red-xiaoshami** [wechat-miniprogram/api-typings#118]
'Promise' only refers to a type, but is being used as a value here. Do you need to change your target library? Try changing the `lib` compiler option to es2015 or later.ts(2585)
小程序是不是不兼容啊？

**Comment by Mister-Hope** [comment]
Promise 是 es6（es2015）引入的啊，你把target调成es5不报错才怪了

**Comment by SgLy** [comment]
试一下在 `tsconfig.json` 里把 `lib` 调整到 es6 呢 @Red-xiaoshami
