### ISSUE TITLE
ReadFileOption的encoding定义

### ISSUE THREAD

**Issue by willing8310** [wechat-miniprogram/api-typings#12]
encoding?:
      | 'ascii'
      | 'base64'
      | 'binary'
      | 'hex'
      | 'ucs2/ucs-2/utf16le/utf-16le'
      | 'utf-8/utf8'
      | 'latin1';

这里的 | 'utf-8/utf8' 应该改为 | 'utf-8' | 'utf8' ，'ucs2/ucs-2/utf16le/utf-16le'也是一样

**Comment by wechat-miniprogram-admin** [comment]
v2.6.5 修复了
