### ISSUE TITLE
请问有计划支持企业微信小程序sdk吗？

### ISSUE THREAD

**Issue by tangshengfei** [wechat-miniprogram/api-typings#122]
现在企业微信小程序项目中，没有这个提示很头疼，只能使用js项目开发。

**Comment by SgLy** [comment]
企业微信小程序里和微信小程序接口一致的部分，包括 wx 接口和页面、组件构造器之类的，这个定义应该是可以直接用的；`wx.qy` 部分接口暂时可以先 any 顶着或者自己简单做一个（因为我看数量好像也不是很大），官方版本我们再关注一下~

**Comment by freeshineit** [comment]
@tangshengfei  我按照官方文档 写了一个企业微信的声明文件 [lib.wx.qy.api.d.t](https://github.com/freeshineit/lib.wx.qy.api/blob/master/lib.wx.qy.api.d.ts)

**Comment by Jungle68** [comment]
不打算支持吗？

**Comment by freeshineit** [comment]
@Jungle68  之前提过PR 被拒绝了，  你可以试着用这个  https://github.com/freeshineit/lib.wx.qy.api

**Comment by Jungle68** [comment]
thinks




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月8日(星期六) 晚上7:20
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [wechat-miniprogram/api-typings] 请问有计划支持企业微信小程序sdk吗？ (#122)





 
@Jungle68  之前提过PR 被拒绝了，  你可以试着用这个  https://github.com/freeshineit/lib.wx.qy.api
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by liwuhou** [comment]
感谢老哥

**Comment by insunilu** [comment]
> @Jungle68 之前提过PR 被拒绝了， 你可以试着用这个 https://github.com/freeshineit/lib.wx.qy.api

感谢老哥
