### ISSUE TITLE
version code issue

### ISSUE THREAD

**Issue by Mister-Hope** [wechat-miniprogram/api-typings#125]
I know we are matching the lib version code. But can we use a standard version code? I have some bots dealing with deps like DependentBot and revonate, and they will think 2.10.3 is greater than 2.10.3-1, also, package like `npm-check-updates` will think that too.

**Comment by Mister-Hope** [comment]
![image](https://user-images.githubusercontent.com/33315834/79752561-17985f80-8347-11ea-914d-f56489c4e81b.png)

**Comment by SgLy** [comment]
2.10.3-1 is actually parsed as "a pre-released version of 2.10.3" according to semver. However, it seems like a semver starts with 2.10.3 but greater than 2.10.3 does not exist, So 2.10.3-1 may be the best choice among all the workarounds, or if you have a better choice, feel free to leave a comment.

By the way, I'm also considering the necessity of keeping typing's version the same as baselib. Baselib's version is not quite compatible with semver, that we add new features into a patch while keeping backward compatibility. So may be it will be better to make typings have its own version?

**Comment by Mister-Hope** [comment]
Yes, just let it has its own version wound be nice ,or we can publish every version with the formate `x.x.x-x`

**Comment by Mister-Hope** [comment]
这个问题有什么进展么？

**Comment by SgLy** [comment]
准备直接上 3.0，不跟基础库版本了

**Comment by Mister-Hope** [comment]
> 准备直接上 3.0，不跟基础库版本了

我的第一反应是微信出3.0基础库了，心一下就凉了hhhh😂

**Comment by SgLy** [comment]
> 我的第一反应是微信出3.0基础库了，心一下就凉了hhhh😂

那没有hhhh，基础库还不知道什么时候上 major 呢
