### ISSUE TITLE
2.11.0 发布有些日子了，何时能更一下？

### ISSUE THREAD

**Issue by Mister-Hope** [wechat-miniprogram/api-typings#130]
有一些改变，比如夜间模式在 `GetSystemInfoSyncResult` 上追加了 `theme`

`App()` 新增了 `onThemeChange` 

接口新增了 wx.saveFileToDisk wx.getPerformance() 等，现在我是自己临时写了个接口凑上了。

**Comment by Mister-Hope** [comment]
@SgLy

**Comment by SgLy** [comment]
发啦，谢谢催更~

**Comment by Mister-Hope** [comment]
Emm, 类型定义能不能再精细一些，比如：

![image](https://user-images.githubusercontent.com/33315834/82554870-4baaae80-9b99-11ea-96e6-3da70632303f.png)

**Comment by Mister-Hope** [comment]
这是我之前的hack
