### ISSUE TITLE
TS 开发时如何使用 Promise?

### ISSUE THREAD

**Issue by yanshouwang** [wechat-miniprogram/api-typings#131]
如图，想要使用 Promise 的时候报错
![image](https://user-images.githubusercontent.com/24455689/82532155-50f50280-9b73-11ea-9e69-e4e7c24504dc.png)

**Comment by yanshouwang** [comment]
找到原因了，项目模板中的 typings 不是最新的，需要手动把最新的 types 替换掉 typings 下的 types 文件夹，这个问题能不能优化一下...每次定义升级都需要手动替换吗，而且文档中也米有相关说明，感觉很迷惑

**Comment by SgLy** [comment]
项目模板中的是固定的，没有跟 npm 和 GitHub 更新，如果需要最新的定义可以试试用 npm 的？

**Comment by yanshouwang** [comment]
现在是不是还不能使用 @types 来安装？

**Comment by yanshouwang** [comment]
还有个问题，Promise.catch 中的参数为什么是 any 呢？这样不好处理异常吧

**Comment by SgLy** [comment]
现在暂时还不能用 `@types` 来装，未来会试试

我也很希望 `Promise.catch` 可以不是 `any`，但遗憾的是 ts 应该是不支持设置这个类型的 Microsoft/TypeScript#7588

**Comment by yanshouwang** [comment]
最后一个问题，下面这段代码里调用方法时传入的对象是个空对象，这种情况下 JS 可以不传参数，但是 TS 里类型检查必须传参，是否可以优化一下？感谢~

``` TS
wx.openBluetoothAdapter({})
      .then(() => wx.getBluetoothAdapterState({}))
      .then(res => this.onAdapterStateChange(res))
      .catch(err => console.log(`index.openAdapter 失败: ${JSON.stringify(err)}`));
```

**Comment by SgLy** [comment]
这个应该是具体接口标注错了，就是 `openBluetoothAdapter` 的参数本来是可省略的，但没有标记。暂时处理可以像你这样加空对象，如果有遇到接口有类似问题的都可以反馈过来，非常感谢~

**Comment by TtTRz** [comment]
> 现在是不是还不能使用 @types 来安装？

现在可以用 @types 安装了

**Comment by SgLy** [comment]
`openBluetoothAdapter` 参数在 3.0.2 里 fix 了，如果没有其他问题的话就 close 啦
