### ISSUE TITLE
快速启动一个TS版本的小程序，在page/index/index.ts报找不到接口的错误

### ISSUE THREAD

**Issue by FrontDream** [wechat-miniprogram/api-typings#132]
![image](https://user-images.githubusercontent.com/47747920/83230686-c76db200-a1bc-11ea-88c7-03d63b17f0ac.png)

问题如上图所示，按照官网的流程，快速启动了一个ts版本的项目，进入到page/index/index.ts，IAppOption没找到，如图所示。麻烦解答是哪里有问题嘛

**Comment by SgLy** [comment]
这个定义在 `typings/index.d.ts` 下面，我刚才试了试工具的快速启动是没问题的，是改过了 `tsconfig.json` 吗？
