### ISSUE TITLE
Component 不能往 this 上加自定义属性

### ISSUE THREAD

**Issue by 1728317209** [wechat-miniprogram/api-typings#133]
Page 可以往 this 上加自定义属性，Component 不可以，能支持吗？
```ts
interface TData {
  name: string;
}

interface TProperty {
  [key: string]: WechatMiniprogram.Component.AllProperty;
  id: NumberConstructor;
}

interface TMethod {
  [key: string]: (...args: any[]) => any;
  setJob: (job: string) => void;
}

Component<TData, TProperty, TMethod>({
  properties: {
    id: Number,
  },

  data: {
    name: '',
  },

  methods: {
    setJob(job) {
      this.job = job; // 不能将类型“string”分配给类型“(...args: any[]) => any”。
    },
  },
});

```
```ts
interface TData {
  id: number;
  name: string;
}

interface TCustom {
  job: string;
  setJob: (job: string) => void;
}

Page<TData, TCustom>({
  data: {
    id: 0,
    name: '',
  },

  job: '',

  setJob(job) {
    this.job = job;
  },
});
```

**Comment by Mister-Hope** [comment]
官方是不支持的，但是你可以在构造器前声明一个对象，在那里存储。

**Comment by 1728317209** [comment]
> 官方是不支持的，但是你可以在构造器前声明一个对象，在那里存储。

🙏

在 global.d.ts 里这样写👇，我试了下是可以的


![image](https://user-images.githubusercontent.com/39460401/83318397-09ebc900-a267-11ea-8d91-4979dcbbc8ff.png)


但是会有 `lib.wx.component.d.ts(25, 14): 'Instance' was also declared here.` 这样标识符重复的报错，这样没关系吗？

**Comment by Mister-Hope** [comment]
我的意思是，你在 Component() 之前声明一个对象就可以了......

1728317209 <notifications@github.com> 于 2020年5月30日周六 11:18写道：

**Comment by 1728317209** [comment]
这样的话，这些就没有了吧

<img width="413" alt="截屏2020-06-02 下午4 35 00" src="https://user-images.githubusercontent.com/39460401/83499033-492c4b00-a4ef-11ea-8542-b504462e3fd4.png">

**Comment by SgLy** [comment]
Component 是不能像 Page 一样在构造参数顶层加自定义参数的，就
```js
Component({
  test: 1,
  methods: {
    fn() {
      this.test // undefined
    }
  }
})
```
要挂自定义参数只能直接 `this.test=1` 这样去操作，当时写定义的时候一是这个推导比较难做，二是以为应该很少会有人这样去用，所以没有专门给它留一个泛型位置。有比较具体的使用情景可以一起看一下吗？

**Comment by 1728317209** [comment]
我们项目里面，一般渲染层用不到的数据，都是 this.xxx 或 this.state.xxx，渲染层用到的数据，才会放到 data 里

**Comment by Mister-Hope** [comment]
我的习惯是在第一行 const state = {} 然后再注册 Component

1728317209 <notifications@github.com> 于 2020年6月2日周二 21:41写道：

**Comment by 1728317209** [comment]
在第一行 const state = {}，这个 state 是所有组件公共的 state

如果 `<list-item />` 组件，就一定要用 this 了。

**Comment by SgLy** [comment]
那我正好来推销一下 [纯数据字段](https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/pure-data.html)

不过话说回来，往自定义组件实例上挂属性既然是可以的，应该还是得想办法支持。下个版本看看加一个泛型 mixin 到实例上解决这个问题吧

**Comment by Mister-Hope** [comment]
> 那我正好来推销一下 [纯数据字段](https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/pure-data.html)
> 
> 不过话说回来，往自定义组件实例上挂属性既然是可以的，应该还是得想办法支持。下个版本看看加一个泛型 mixin 到实例上解决这个问题吧

2.8.2劝退了

**Comment by 1728317209** [comment]
感谢🙏

**Comment by 1728317209** [comment]
我们基础库还是 1.9.4 😂

**Comment by Mister-Hope** [comment]
> 我们基础库还是 1.9.4 😂

我基础库2.5.2

**Comment by SgLy** [comment]
2.8.3 以上都已经 98% 了呀😂

**Comment by 1728317209** [comment]
> 不过话说回来，往自定义组件实例上挂属性既然是可以的，应该还是得想办法支持。下个版本看看加一个泛型 mixin 到实例上解决这个问题吧

现在不用声明 TData、TProperty、TMethod，可以推断出来

如果“加一个泛型 mixin 到实例上解决这个问题”，还能这样推断出来吗？

![image](https://user-images.githubusercontent.com/39460401/83623844-6bdc6380-a5c4-11ea-8b60-2c4dbbd3638a.png)

**Comment by SgLy** [comment]
已经在新版本里加上了，用例：https://github.com/wechat-miniprogram/api-typings/blob/1ae404c/test/issue.test.ts#L277-L307

**Comment by SgLy** [comment]
暂且先关闭了，如果有问题再重新打开吧

**Comment by ethanyifan** [comment]
> 已经在新版本里加上了，用例：https://github.com/wechat-miniprogram/api-typings/blob/1ae404c/test/issue.test.ts#L277-L307

请问如何给properties中的值提供默认值呢？我想用比如
`job: { type:Number, value:0 }`
这种写法，在IProperty中应该如何定义呢？

**Comment by SgLy** [comment]
> 这是啥解决方案啊，本来 IData, IProperty, IMethod 是能自动推导的，现在为了声明 ICustomInstanceProperty，前面几个泛型也得声明了，你们弄了这个方案后自己实际用过吗？不觉得别扭吗。。。

确实是很别扭，主要是基于这些原因：
1. 小程序基础库是覆盖式发布，小程序不能自己决定使用哪个版本的基础库，因此框架相关的接口必须保持稳定，不能做破坏性改动；
2. 基于第一点，类型定义只能去描述现有接口，不能为了方便推导或者易用而改变实际的接口形式和参数，因为破坏性的改动无法落实到实际实现上；
3. 自定义属性目前通过 `this.prop = x` 挂载，这个无法推导，只能传入；在第二点的基础上，要维持原有泛型自动推导只能让同一个函数的多个泛型部分传入、部分推导，而这个特性目前 TypeScript 还没法实现（microsoft/TypeScript#26242）

目前这套框架接口因为设计的时间比较早，那时候 TS 相对来说不像现在这么流行，因此接口对 TS 并不太友好；现在这套方案是考虑以上限制下能解决问题的一种方案，但是由于我水平有限，确实很别扭；如果有更好的方案也欢迎提出，可以再改进这份定义

我们这两年重新设计的新版框架接口中有考虑这个用法了（wechat-miniprogram/glass-easel#70），这份定义后面也会补上链式调用的支持（#315）
