### ISSUE TITLE
requestSubscribeMessage does not exist on type wx

### ISSUE THREAD

**Issue by geoffliu** [wechat-miniprogram/api-typings#137]
`requestSubscribeMessage` has been in stable API since 2.4.4. Even if when targeting earlier versions of base API, I'd expect it to be optional, at least.

**Comment by SgLy** [comment]
It does exist, and [test case](https://github.com/wechat-miniprogram/api-typings/blob/94a01f9/test/api-doc.test.ts#L3034-L3042) is also passed.

**Comment by geoffliu** [comment]
My installed version: 

`"miniprogram-api-typings": "2.8.3-1"`

I'm getting the following message: 

`Property 'requestSubscribeMessage' does not exist on type 'Wx'.`

Code snippet: 

```
wx.requestSubscribeMessage({
        tmplIds: [
         ...
        ],
        complete: () => {...}
})
```

**Comment by SgLy** [comment]
How about updating to latest version to solve it?

**Comment by geoffliu** [comment]
哦？typing版本不是应该用基础库版本吗？看到readme的建议

**Comment by SgLy** [comment]
因为向前兼容，后来也偷懒了，修的有些 bug 没再给旧的版本打一份……用最新的吧，后面版本号也准备不跟基础库版本同步了

**Comment by geoffliu** [comment]
哦，那好的。那这个issue就没事了
