### ISSUE TITLE
Should wx.request have a type parameter?

### ISSUE THREAD

**Issue by geoffliu** [wechat-miniprogram/api-typings#138]
Currently, the `res.data` field in the success callback has type `'string | Record<string, any> | ArrayBuffer`. This means to properly use this, I have to do this (pseudocode):

```
if (typeof res.data is string or array buffer) {
  raise error
}
use res.data as type any object
```

There are two problems with this. 1. I know my backend API returns JSON in the success case, so the string and ArrayBuffer cases are never actually in use. 2. res.data is simply any object, I can't specify its type without doing an explicit cast every time. 

Proposal: define wx.request as something similar to the following:
```
request<T>({
  success: ({ data: T, ... }) => void,
  ...
})
```

While we're at it, it'd be useful to define an error type as well, for the fail callback.

**Comment by SgLy** [comment]
`wx.request` can have a generic, this will be tracked in #177, closing duplicated
