### ISSUE TITLE
有没有不需要 types 文件夹，而是使用 node_modules 的方案？

### ISSUE THREAD

**Issue by beary** [wechat-miniprogram/api-typings#139]
目前声明文件总是和项目代码一起提交，感觉这种做法非常不地道，如果未来某一天新增了 api ，还要手动复制粘贴新的声明文件。能否够将它放到`node_modules`文件夹中呢？

**Comment by Mister-Hope** [comment]
......正常不就是安装依赖么？

**Comment by listenzz** [comment]
@beary  我们在 tsconfig.json 中添加如下配置

```json
"typeRoots": ["./node_modules/@types", "./node_modules/miniprogram-api-typings"],
```

**Comment by beary** [comment]
@listenzz 谢谢，我试了下可以
也找到另一种方法，直接在 App.ts 中
```ts
import 'miniprogram-api-typings'
```

**Comment by beary** [comment]
@Mister-Hope 小程序开发工具最新版初始化 typescript 项目用的是 types 文件夹存放，并未放在 node_modules 中
