### ISSUE TITLE
Should `counterclockwise` in `CanvasContext.arc`'s params be `boolean` instead of `number` ?

### ISSUE THREAD

**Issue by malash** [wechat-miniprogram/api-typings#14]
Should `counterclockwise` in `CanvasContext.arc`'s params be `boolean` instead of `number` ?

Since there is no demo in document I'm not sure which one is correct.

WeChat Mini Program document: https://developers.weixin.qq.com/miniprogram/dev/api/CanvasContext.arc.html

MDN: https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/arc

**Comment by wechat-miniprogram-admin** [comment]
You are right, i will fix it
