### ISSUE TITLE
2.12.0 support

### ISSUE THREAD

**Issue by Mister-Hope** [wechat-miniprogram/api-typings#141]
Hi bro, it seems that you are still updating 2.11.2, while 2.12.0 has been updated for a while.

Update API like:

- https://developers.weixin.qq.com/miniprogram/dev/api/base/update/wx.updateWeChatApp.html
- https://developers.weixin.qq.com/miniprogram/dev/api/device/bluetooth-ble/wx.makeBluetoothPair.html
- https://developers.weixin.qq.com/miniprogram/dev/api/media/video/wx.openVideoEditor.html
- https://developers.weixin.qq.com/miniprogram/dev/reference/api/Page.html#onShareTimeline

**Comment by SgLy** [comment]
We will update to 2.11.3 soon, and 2.12.0 after baselib grey-release done~

**Comment by Mister-Hope** [comment]
2.12.0 好像已经全量推送了吧？
另外个人认为灰度的库也是尽快发比较好。毕竟灰度之后API也不会出现什么改变。

**Comment by Mister-Hope** [comment]
我又来催更了，我的一些用户的基础库已经收到2.12.0了，不知道是不是你们全量推送了。

**Comment by SgLy** [comment]
> 另外个人认为灰度的库也是尽快发比较好。毕竟灰度之后API也不会出现什么改变。

灰度的库理论上是灰度完才一起放出文档和定义的，毕竟灰度中还不算是可用的状态，这个要不要调整我再跟他们讨论吧

> 我又来催更了

3.0.0 更新啦，@types 那边要提 pr，可能会久一点

**Comment by Mister-Hope** [comment]
等等，这个库就是面向开发者的，每次灰度库不也是让开发者提前进行适配跟进新功能，然后外加帮忙测试，找找有没有bug，看看之前的旧功能兼容性好不好呀。所以跟灰度一起走不是正常的么？我不记得灰度中改动过什么api接口啊，基本上发公告开始灰度开发者就定下来了
