### ISSUE TITLE
Cannot find namespace 'wx'

### ISSUE THREAD

**Issue by 15669028801** [wechat-miniprogram/api-typings#142]
![image](https://user-images.githubusercontent.com/35586321/88125993-1f47f880-cc03-11ea-899e-85476d09785c.png)

app.ts 中的wx 不存在

versions: ^2.11.0-1

**Comment by Saul-Mirone** [comment]
去掉/types

**Comment by 15669028801** [comment]
> 去掉/类型

试过了，无效、。是ts的范围没配置对，感觉

**Comment by SgLy** [comment]
命名空间现在调整成 `WechatMiniprogram` 啦

**Comment by 15669028801** [comment]
> 命名空间现在调整成`WechatMiniprogram`啦

是的、。里面的都改了，外面的没反应过来，谢谢
