### ISSUE TITLE
[Bug] wx.startDeviceMotionListening 参数应为可选

### ISSUE THREAD

**Issue by Mister-Hope** [wechat-miniprogram/api-typings#143]
![image](https://user-images.githubusercontent.com/33315834/88163890-e67d4300-cc45-11ea-93dc-af5e92d1a0b1.png)
所有参数均为可选。且不传入空对象运行不报错

同理，还有跟他一起的 wx.startGyroscope wx.startAccelerometer 等也有同样的问题，不过他们的 stop 是正常的。

另外日常催更 2.11.3 2.12.0

**Comment by Mister-Hope** [comment]
![image](https://user-images.githubusercontent.com/33315834/88387755-bd93b400-cde5-11ea-9700-7268e11ddac0.png)
zhe'ge这个也是这个问题，是跟其他api一样，不传参数取消所有监听。

**Comment by SgLy** [comment]
还有其他发现的话也都一起列出来吧，我都去改一改

**Comment by Mister-Hope** [comment]
mapContext.moveToLocation

**Comment by Mister-Hope** [comment]
wx.offUserCaptureScreen 的 callback

**Comment by SgLy** [comment]
上面的都 fix 了

**Comment by Mister-Hope** [comment]
wx.openSetting

**Comment by SgLy** [comment]
`openSetting` fixed in 3.1.1

之前这里集中处理过一次，看还有没有发现，没有的话就先把它 close 了
