### ISSUE TITLE
interface ComponentOptions have no pureDatapattern property?

### ISSUE THREAD

**Issue by oloshe** [wechat-miniprogram/api-typings#146]
![image](https://user-images.githubusercontent.com/40467840/90461558-264a2400-e139-11ea-9def-4b8ce92e0d7b.png)

The IDE will promt error  when using the pureDataPattern, and it will also throw an error when compile ts files.
`Type '{ pureDataPattern: RegExp; }' is not assignable to type 'ComponentOptions'`

**Comment by wechat-miniprogram-admin** [comment]
It's added since Dec. 19, try to update your typings to a newer version? You can check out `README.md` of this repo for instructions.
