### ISSUE TITLE
onShareAppMessage 中使用 this 关键字会导致类型推断无法正常使用。

### ISSUE THREAD

**Issue by DengMingHao** [wechat-miniprogram/api-typings#148]
问题： onShareAppMessage 中使用 this 关键字会导致类型推断无法正常使用
使用编辑器： vs code v1.48.1
miniprogram-api-typings版本: v3.0.2

![QQ截图20200821171430](https://user-images.githubusercontent.com/19725882/90874659-99ba9280-e3d2-11ea-8a5d-c1f6d0edaf40.png)

======================================

![QQ截图20200821171609](https://user-images.githubusercontent.com/19725882/90874669-9d4e1980-e3d2-11ea-9ff4-2495521e183c.png)

**Comment by wechat-miniprogram-admin** [comment]
和 #90 提到的问题差不多，我试了试，这两种办法标注类型都可以
```ts
Page({
  data: { a: '123' },
  onShow() {
    expectType<() => number>(this.fn)
  },
  fn() { return 1 },
  onShareAppMessage(): WechatMiniprogram.Page.ICustomShareContent {
    return { title: this.data.a, imageUrl: '', path: '' }
  },
})
```
或者
```ts
Page({
  data: { a: '123' },
  onShow() {
    expectType<() => number>(this.fn)
  },
  fn() { return 1 },
  onShareAppMessage() {
    const ret: WechatMiniprogram.Page.ICustomShareContent
       = { title: this.data.a, imageUrl: '', path: '' }
    return ret
  },
})
```
