### ISSUE TITLE
Wrong `AuthSetting` type.

### ISSUE THREAD

**Issue by malash** [wechat-miniprogram/api-typings#15]
`AuthSetting` type is wrong.

It should be:

```ts
interface AuthSetting {
  ['scope.userInfo']: boolean;
  ...
}
```

And here is a use case from [wx.getSetting](https://developers.weixin.qq.com/miniprogram/dev/api/wx.getSetting.html):

```ts
wx.getSetting({
  success(res) {
    console.log(res.authSetting)
    // res.authSetting = {
    //   "scope.userInfo": true,
    //   "scope.userLocation": true
    // }
  }
})
```

Document: https://developers.weixin.qq.com/miniprogram/dev/api/AuthSetting.html

**Comment by wechat-miniprogram-admin** [comment]
v2.6.5 修复了
