### ISSUE TITLE
有办法支持所有组件标签的types吗？

### ISSUE THREAD

**Issue by oodzchen** [wechat-miniprogram/api-typings#153]
比如`audio`、`rich-text`以及`checkbox`之类的

**Comment by SgLy** [comment]
因为是 ts 的定义文件，所以最多只能支持到这些组件的事件的 types；要支持 wxml 里的补全和类型的话靠定义文件肯定是不可能的了

**Comment by oodzchen** [comment]
> 因为是 ts 的定义文件，所以最多只能支持到这些组件的事件的 types；要支持 wxml 里的补全和类型的话靠定义文件肯定是不可能的了

如果爬取微信开放文档里的数据应该可以生成这些types文件。另外，这些文档是微信的官方开发团队制作的，按理说他们来制作types文件应该更方便，直接从程序里提取即可。或者有类似的vscode自动提示插件也行，参考 html 标签的自动补全功能。

**Comment by SgLy** [comment]
@oodzchen 我们确实有这些数据，但是 ts 的定义文件只能支持 ts 代码呀，wxml 已经是另外一种语言了，定义文件没法直接对它进行支持的。

最新版本的工具应该已经支持 wxml 的标签和属性补全了，可以下载最新版本试一试

**Comment by oodzchen** [comment]
@SgLy 好的，我找找看
