### ISSUE TITLE
wx.requestPayment signType 需要支持 RSA 加密方式

### ISSUE THREAD

**Issue by mingming031** [wechat-miniprogram/api-typings#154]
依照 v3 版本的接口声明 signType 的支持方式需要变更为
        signType: 'HMAC-SHA256' | 'MD5' | 'RSA',

小程序文档：
https://pay.weixin.qq.com/wiki/doc/apiv3/wxpay/ecommerce/e_transactions/chapter3_8.shtml

原声明文件：
https://github.com/wechat-miniprogram/api-typings/blob/94a01f947ed6e9567672ff955121b640af75d603/types/wx/lib.wx.api.d.ts#L3753

**Comment by SgLy** [comment]
我确认了一下，小程序目前的 `wx.requestPayment` 还是 v2 接口，这个 `signType` 应该是没有问题的

**Comment by mingming031** [comment]
按照微信支付 v3版本的接口声明，RSA的签名方式已经支持了，实测小程序 wx.requestPayment 已经支持 v3 声明的 RSA 签名方式。

**Comment by SgLy** [comment]
确认过了，确实支持，已经在 903ddd46806562fecf9d4b59572c69edd4980e39 和 npm 3.1.2 中修复，非常感谢

**Comment by mingming031** [comment]
fixed by
https://github.com/wechat-miniprogram/api-typings/commit/903ddd46806562fecf9d4b59572c69edd4980e39#diff-2bc80e81787d294041b1b460b8c77b62R4361
