### ISSUE TITLE
getOpenerEventChannel 定义问题

### ISSUE THREAD

**Issue by kawaiiz** [wechat-miniprogram/api-typings#156]
Component<InitData, InitProperty, InitMethod>。
当由component创建的页面page，    onLoad等生命周期以及一些在this上的方法需要自己手动在每个页面的InitMethod添加，这个其实问题不大。
现在就是 getOpenerEventChannel 这个方法，我需要使用，所以需要写在type:InitMethod里，
然后我需要在methods里加上getOpenerEventChannel 方法，不然ts会报错，显示缺少该方法，
我选择在methods上加一个名为getOpenerEventChannel的方法，避免ts报错。
但是在methods加上以后，在onload里console.log(this)，显示我的写的getOpenerEventChannel方法覆盖了在this上的getOpenerEventChannel 方法。

现在就出现，我不在InitMethod加getOpenerEventChannel 方法，调用处会报错，显示函数未定义，在methods加上该方法，函数又会被覆盖。
现在是在InitMethod里使用[key:string]:value,不定义这个函数了。
希望能改一下。

**Comment by SgLy** [comment]
本质上和 #113 是同一个问题，不过这个好像更严重一点 orz

我想一想有没有办法，给 `Component` 做页面的情况一个比较特殊的支持
