### ISSUE TITLE
wrong type for WxSaveFileSuccessCallbackResult.savedFilePath

### ISSUE THREAD

**Issue by xyning** [wechat-miniprogram/api-typings#157]
https://github.com/wechat-miniprogram/api-typings/blob/07a400f4671610e17cbf9ceddea1ce74f0c9bfc1/types/wx/lib.wx.api.d.ts#L6164
should be `string` instead

**Comment by SgLy** [comment]
fixed with 903ddd46806562fecf9d4b59572c69edd4980e39 and 3.1.2
