### ISSUE TITLE
[Bug]分享到朋友圈的ICustomTimelineContent定义不正确

### ISSUE THREAD

**Issue by bigmeow** [wechat-miniprogram/api-typings#159]
https://github.com/wechat-miniprogram/api-typings/blob/903ddd46806562fecf9d4b59572c69edd4980e39/types/wx/lib.wx.page.d.ts#L179

此处`query`正确定义应该为：
```ts
interface ICustomTimelineContent {
        /** 自定义标题，即朋友圈列表页上显示的标题。默认值：当前小程序名称 */
        title?: string
        /** 自定义页面路径中携带的参数，如 `path?a=1&b=2` 的 “?” 后面部分 默认值：当前页面路径携带的参数 */
        query?: string
        /** 自定义图片路径，可以是本地文件路径、代码包文件路径或者网络图片路径。支持 PNG 及 JPG。显示图片长宽比是 1:1。默认值：默认使用小程序 Logo*/
        imageUrl?: string
    }
```

**Comment by Mister-Hope** [comment]
似乎字符串和对象格式的参数均是支持的。在社区文档里的某个案例给的是对象格式。

**Comment by SgLy** [comment]
确实不对，应该是只支持 `string`，不支持 `object`……

@Mister-Hope 有印象案例在哪里的话贴出来看看是不是当时给错了😂

**Comment by SgLy** [comment]
已在 61b6980 和 3.1.3 中修复

**Comment by Mister-Hope** [comment]
> 确实不对，应该是只支持 `string`，不支持 `object`……
> 
> @Mister-Hope 有印象案例在哪里的话贴出来看看是不是当时给错了😂

主要是我现在用着呢，而且我的写法都是object的格式。而且是可以正确分享的。我那里面的参数完全决定了显示什么。

**Comment by Mister-Hope** [comment]
你可以看一下小程序in东师。基本上所有页面都支持分享朋友圈。分享的结果都是正常的，都是object的格式写的。

**Comment by bigmeow** [comment]
3.x 版本各个小版本变动也挺大的，而`@types/wechat-miniprogram` 还只是3.0版本，一些知名库已经用它了，导致出现了一些问题，建议同步更新下版本吧。。。
@SgLy

**Comment by bigmeow** [comment]
https://github.com/youzan/vant-weapp/issues/3672

**Comment by SgLy** [comment]
published `@types/wechat-miniprogram@3.2.0` (same as `miniprogram-api-typings@3.2.2`)
