### ISSUE TITLE
Does `wx.removeStorage` has success res data ?

### ISSUE THREAD

**Issue by malash** [wechat-miniprogram/api-typings#16]
Is it a bug in demo ?

```ts
wx.removeStorage({
  key: 'key',
  success(res) {
    console.log(res.data)
  }
})
```

`res.data` is `undefined` in runtime.

https://developers.weixin.qq.com/miniprogram/dev/api/wx.removeStorage.html

**Comment by wechat-miniprogram-admin** [comment]
There is a error here. The success callback only has res.errMsg
