### ISSUE TITLE
@types/wechat-miniprogram 未同步

### ISSUE THREAD

**Issue by yangmingshan** [wechat-miniprogram/api-typings#160]
@types/wechat-miniprogram 已经落后几个版本了，有更新的计划吗？

**Comment by SgLy** [comment]
同步 3.1.5 到 `@types` 的 3.1 了 DefinitelyTyped/DefinitelyTyped#49231

因为提 PR 比较繁琐，所以有点迟了，之后我们整理一下流程，提高点同步频率

**Comment by xhwgood** [comment]
你们这真的提高同步频率了吗？已经落后俩个版本了
