### ISSUE TITLE
[Bug]Component中的methods和properties类型在某些场景下推断错误

### ISSUE THREAD

**Issue by Lienviws** [wechat-miniprogram/api-typings#161]
系统版本：macos 10.14.6
ide: vscode 1.50.1
ts版本：4.0.3
api-typings版本：3.1.3

当在`Component`内的`methods`对象里的方法返回`this.data`里的值时，`methods` 类型就直接推断成 `Record<string, (...args: any[]) => any>` 了，导致`methods`下的方法访问不到`methods`的属性，如下代码所示

```ts
Component({
  properties: {
    bar: String
  },
  data: {
    foo: 123,
  },
  methods: {
    getDataOrPoperty () {
      /** 
       * 没有下面的 return 时，methods 是这个类型
       (property) methods?: {
            getPoperty(): void;
            test(): void;
        } | undefined
       */
      return this.data.bar // 出参涉及 properties 或者 data，methods 类型变成 Record<string, (...args: any[]) => any>
    },
    test () {
      this.getDataOrPoperty // this.getDataOrPoperty 推断成了any
    },
  }
})
```

在上面的基础上，另外还有个case，会导致`properties`的属性访问不到：

```ts
Component({
  properties: {
    bar: {
      type: Object,
      value: { skuNum: 0 },
      observer () {} // 如果加上observer，properties的类型变成 Record<string, WechatMiniprogram.Component.AllProperty>
    }
  },
  data: {
    foo: 123,
  },
  methods: {
    getDataOrPoperty () {
      return this.data.foo // 前置条件：出参涉及 properties 或者 data
    },
    test () {
      this.data.bar // this.data.bar 推断成了any
    },
  }
})
```

**Comment by SgLy** [comment]
和 #90 是差不多同样的问题，小程序页面和组件的注册器跟 Vue 的组件一样有一定的循环性（比如方法的类型和数据、属性的类型推导互相影响），这种时候 ts 就会推导失败，可以试试手动标注部分类型来解决，例如你这个例子标注 `getDataOrProperty(): number` 应该能解决？

**Comment by Mister-Hope** [comment]
Sgly 说的没有错误，自从给 `@vue/composition-api` 提了一个修复类型推导 bug 的 issue 之后理解很深刻。你需要避免循环引用。所以所有涉及到其他泛型的返回值应当手动标注。

**Comment by Lienviws** [comment]
通过指定return类型可以解决，但是coding的时候还得手动带个尾巴不能自动推导总归还是不太舒服。

我觉得应该是通过ThisType绑在一起的作用域推导出来的值哪里有点问题，不是循环太复杂了，可以看下这个例子：
```ts
type MethodOption = Record<string, (...args: any[]) => any>

type IOptions<M extends MethodOption> = {
    methods: M
} & ThisType<M & {testData: string}>

const fn = <M extends MethodOption>(options: IOptions<M>) => {}
fn({
    // type: Record<string, (...args: any[]) => any>
    methods: {
        foo () {
            return this.testData
        }
    },
})

```
另外如果把MethodOption的形状改一下，似乎可以解决这个问题：
```ts
// type MethodOption = Record<string, (...args: any[]) => any>
type MethodOption = Record<string, Function>

type IOptions<M extends MethodOption> = {
    methods: M
} & ThisType<M & {testData: string}>

const fn = <M extends MethodOption>(options: IOptions<M>) => {}
fn({
    methods: {
        foo () {
            return this.testData
        }
    },
})
```

**Comment by SgLy** [comment]
把 `(...args: any[]) => any` 改成 `Function` 确实有用

没看过这里 ts 具体的工作原理，我猜测是编译器为了看 `foo` 的类型能不能赋值给 `(...args: any[]): any`，就去获取 `this` 的类型来确定返回值，而决定 `this` 的类型的时候又绕回到 `foo` 的类型上了，它就放弃了（`methods` 那里显示的类型是泛型的默认值）；但改成 `Function` 之后，编译器可能有特殊的逻辑让 `foo` 赋值给 `Function` 这里直接通过了，所以就正常跑起来了……感觉这是不是可以提个 issue 给 ts 那边😂

这里改成 `Function` 应该是正确的，好像也没看到说不推荐（主要是 `String`, `Boolean`, `Object` 之类的都是不推荐的），要不你提个 pr 把它改了？或者下版本我一起改 @Lienviws

**Comment by Mister-Hope** [comment]
据我所知，{} 和 Function 在 @typesript-eslint 那边都是不推荐的。

**Comment by Lienviws** [comment]
Function在@typesript-eslint确实不推荐，因为在地位上有点类似"Function any"的存在，尽管它的types充分描述了Function的原型。

不过在 Record<string, (...args: any[]) => any> 这个结构里，泛型的第二个参数正好需要一个"能涵盖所有场景"、"function类型"的types，Function正好符合这么一个需求，而且相对去掉MethodOption的限制，Function也可以限制传入的值是function类型。

**Comment by SgLy** [comment]
> Function在@typesript-eslint确实不推荐，因为在地位上有点类似"Function any"的存在，尽管它的types充分描述了Function的原型。
> 
> 不过在 Record<string, (...args: any[]) => any> 这个结构里，泛型的第二个参数正好需要一个"能涵盖所有场景"、"function类型"的types，Function正好符合这么一个需求，而且相对去掉MethodOption的限制，Function也可以限制传入的值是function类型。

已在 5b107ded984e27ca3f92ad2a0d9f1be85aefee92 和 3.2.3 中处理
