### ISSUE TITLE
Nfc ConnectFailCallback 等的定义与实际不符

### ISSUE THREAD

**Issue by tolking** [wechat-miniprogram/api-typings#162]
Nfc 中 `connect` 等相关接口调用失败的回调函数中的返回值定义与实际值不同

当前定义

``` ts
interface GeneralCallbackResult {
    errMsg: string
}
type ConnectFailCallback = (res: GeneralCallbackResult) => void
```

然而实际上返回是，如下面的例子

``` ts
{errMsg: "connect:fail:NFC tag has not been discovered", errCode: 13013}
```

我个人认为 `GeneralCallbackResult` -> `Nfcrwerror`

``` ts
type ConnectFailCallback = (res: Nfcrwerror) => void
```

**Comment by Mister-Hope** [comment]
不止这一个接口，所有的接口都没有具体的定义，错误消息可能存在的字符串。

我个人觉得也没有必要进行定义，反正你错了的话就走错误的流程，然后如果你想对特定的错误消息进行特定的逻辑的话，你就自己判断就好了。

我个人认为定义文件没有必要把所有接口的所有可能出现的错误文件都用列举的方式列出来。

**Comment by tolking** [comment]
我的意思是现在的定义 GeneralCallbackResult  缺少了 `errCode: number`，实际返回是存在的。缺失后不好处理错误。

Nfcrwerror 定义了，却没有使用。我认为应该是 Nfcrwerror 而不是 GeneralCallbackResult。

**Comment by SgLy** [comment]
收到，这里之前因为接口太多，所以文档上只在 `wx.getNFCAdapter` 那里注了错误码，具体接口没标注，结果定义这边也跟着没了；我们确认一下哪些具体接口需要标注之后加上

**Comment by SgLy** [comment]
已在 c7fb54c 和 npm 3.2.0 中修复
