### ISSUE TITLE
构建 npm 提示 未找到 npm 包入口文件

### ISSUE THREAD

**Issue by zhangjie2012** [wechat-miniprogram/api-typings#163]
错误提示：

```
node/modules/@types/wechat-miniprogram/index.js: 未找到npm包入口文件。
```

实际 modules 下的目录是包含 `index.d.ts` 文件的。

**Comment by Mister-Hope** [comment]
它并不需要作为一个npm包去处理。请检查你的操作。

如果你有需要构建的npm包的话，请把它放在外层，用 `miniprogramRoot` 指定小程序目录。

**Comment by Mister-Hope** [comment]
```
node_modules/
  miniprogram-api-typings/
app/
  node_modules/
  ... // your other file
project.config.json // 指定 `miniprogramRoot` 为 `app/`
tsconfig.json // 配置 types
```

**Comment by zhangjie2012** [comment]
![image](https://user-images.githubusercontent.com/2450412/97451961-38351800-196f-11eb-822b-7910e9310c78.png)
我的目录结构是这样的，需要使用 npm，安装了 @vant/weapp.

**Comment by zhangjie2012** [comment]
之前一直是可用的，今天重新构建了一下就不行了。 期间升级了一下小程序开发工具，但是后来回退也没用。

**Comment by Mister-Hope** [comment]
你用的是 @types 那个包是吧？不好意思没看仔细，建议删除重新 npm install 或 yarn install 试试。那个包更新周期挺长的，建议还是用 `wechatminiprogram-api-typings` 这个包。

用那个包需要把它拿到小程序目录外面去。也就是说你是这样的结构:
![image](https://user-images.githubusercontent.com/33315834/97452761-083a4480-1970-11eb-88f2-270c91fdfc3a.png)

**Comment by zhangjie2012** [comment]
我没有使用 `@types` 包，只用了 `@vant/weapp`。

package.json 文件内容：

```
{
  "name": "diary",
  "version": "1.0.0",
  "description": "",
  "main": "app.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "https://e.coding.net/a404/diary/client.git"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@vant/weapp": "^1.5.0"
  }
}
```

**Comment by zhangjie2012** [comment]
删除所有的 npm 相关，重新构建都试过了，不顶用。我感觉是 vant/weapp 与新版本开发工具不匹配的问题。

**Comment by zhangjie2012** [comment]
@Mister-Hope 

https://github.com/youzan/vant-weapp/issues/3699

看这个 issue，**忽略即可**， 我 x。

**Comment by SgLy** [comment]
定义包应该放在 `devDependencies` 里面，因为只有开发的时候要用到，我看现在 `@vant/weapp` 是放在了 `dependencies` 里面，导致工具认为这个包是线上需要用到的，尝试找入口构建但没找到导致的

https://github.com/youzan/vant-weapp/blob/31aacedd5b8d9ebf2419afc77993d7fbfe841e0d/package.json#L97-L99

**Comment by zhangjie2012** [comment]
@SgLy 对的。

我回退到 `1.5.0` 版本就没这个问题了。
