### ISSUE TITLE
requirePlugin 缺少一个全局的定义

### ISSUE THREAD

**Issue by henrycjchen** [wechat-miniprogram/api-typings#164]
typescript 运行时出现以下错误：
```
error TS2304: Cannot find name 'requirePlugin'
```

修改方式：需要添加全局定义
```
declare function requirePlugin<T>(name:string): T
```

**Comment by SgLy** [comment]
fixed with f704467 and npm version 3.1.6

**Comment by henrycjchen** [comment]
我看只更新了包 【miniprogram-api-typings】，【@types/wechat-miniprogram】这个包没更新哦，@types 包什么时候会更新呀？

**Comment by SgLy** [comment]
published `@types/wechat-miniprogram@3.2.0` (same as `miniprogram-api-typings@3.2.2`)
