### ISSUE TITLE
require定义问题

### ISSUE THREAD

**Issue by anotherso1a** [wechat-miniprogram/api-typings#165]
当使用第三方基于webpack的库进行小程序开发时，会使用到require.context等方法。

![image](https://user-images.githubusercontent.com/38176179/98094933-e20f2a00-1ec4-11eb-80d8-cc6586241611.png)

当使用这些方法时会报错，并且由于定义的问题，没办法进行扩展：

![image](https://user-images.githubusercontent.com/38176179/98095025-02d77f80-1ec5-11eb-8cdd-75c3e16ce830.png)

建议将require的定义改为接口模式，以便在其他环境下开发时能进行声明合并。

**Comment by SgLy** [comment]
如果我没理解错的话，这里的 `require` 应该是 webpack 的 `require`，在打包之后的代码中是不存在的是吗？用 webpack 来做打包的话，还会不会在打包后的代码中生成 `require`？

**Comment by anotherso1a** [comment]
是的，这个是webpack的require方法，打包之后不会调用微信小程序的require。

但是在编写代码的过程中，和微信定义的require是重名的，需要对定义进行扩展。

**Comment by SgLy** [comment]
因为实际运行时的 `require` 并不具有这些字段以及多出来的参数，我倾向于不直接去改 `require` 的定义，只在需要的时候修改它；现在的情况下，能通过在项目里的定义文件里重新 `declare function require` 来覆盖现有的定义吗？

**Comment by anotherso1a** [comment]
文档看漏了，确实是可以通过 `namespace fn-name` 来扩展函数，一开始我以为只能扩展`interface`。

https://www.tslang.cn/docs/handbook/declaration-merging.html
