### ISSUE TITLE
CanvasRenderingContext2D missing

### ISSUE THREAD

**Issue by geoffliu** [wechat-miniprogram/api-typings#167]
`CanvasRenderingContext2D` is used here: https://github.com/wechat-miniprogram/lottie-miniprogram/blob/master/src/index.d.ts#L8, and there could be other uses for that type as well. 

Normally I would get that type by adding the `dom` lib in Typescript, but I can't do that with miniprogram-api-typing installed, because miniprogram-api-typing has definitions for console, which conflicts with the `dom` lib.

**Comment by SgLy** [comment]
New canvas typing is WIP, track in #111
