### ISSUE TITLE
`CanvasContext.draw`'s params should be optional.

### ISSUE THREAD

**Issue by malash** [wechat-miniprogram/api-typings#17]
`CanvasContext.draw`'s params should be optional. The following usages should be all correct:

```ts
ctx.draw();
ctx.draw(true);
ctx.draw(true, () => {});
```

https://developers.weixin.qq.com/miniprogram/dev/api/CanvasContext.draw.html

**Comment by wechat-miniprogram-admin** [comment]
fixed at v2.6.5
