### ISSUE TITLE
三处定义报错

### ISSUE THREAD

**Issue by SeLiNnnn** [wechat-miniprogram/api-typings#170]
1.lib.wx.api.d.ts
![image](https://user-images.githubusercontent.com/32994916/101271368-08beca00-37bd-11eb-898c-bba1822ea66d.png)

手动改成了string

2.lib.wx.behavior.d.ts

![image](https://user-images.githubusercontent.com/32994916/101271393-3e63b300-37bd-11eb-9ce2-de5354a93295.png)

找不到这个Omit,参考了新建项目自带的typings，也没有这个东西，只好先注释了

**Comment by SeLiNnnn** [comment]
还忘了一个，一开始的IAppOption找不到，手动从typings复制了一份到index.d.ts
![image](https://user-images.githubusercontent.com/32994916/101271456-cf3a8e80-37bd-11eb-9034-1f6303e673b1.png)

**Comment by Mister-Hope** [comment]
Omit是typescript es5 lib的内置类型，如果你找不到，建议自查typescript，另外我记得current这个好像已经fixed了

**Comment by SeLiNnnn** [comment]
> Omit是typescript es5 lib的内置类型，如果你找不到，建议自查typescript，另外我记得current这个好像已经fixed了

好的，已经更新了npm包和ts，前两个问题已经解决了，感谢

**Comment by SgLy** [comment]
`IAppOption` 这个我记得是 quickstart 里作为 `App` 的泛型传进去的，因为 quickstart 里在 App 上挂了这两个属性（没记错的话好像是 `this.globalData.userInfo = ` 和 `getApp().userInfoReadyCallback = `）；如果你的项目里 App 上没有这两个属性，直接去掉就好了

**Comment by SeLiNnnn** [comment]
> `IAppOption` 这个我记得是 quickstart 里作为 `App` 的泛型传进去的，因为 quickstart 里在 App 上挂了这两个属性（没记错的话好像是 `this.globalData.userInfo = ` 和 `getApp().userInfoReadyCallback = `）；如果你的项目里 App 上没有这两个属性，直接去掉就好了

嗯！是的 我需要用到 而且还想扩展
App<IAppOption>({
  globalData: {
    userInfo: undefined
  }
}

**Comment by SgLy** [comment]
就写在你自己的项目里就好了，app.ts 里也行，或者你自己建一个 types.d.ts 跟你其他的类型定义在一起也行；就这个不是默认所有小程序都会有的，你按照你的需要改它就好了，所以没有加到定义库里面去
