### ISSUE TITLE
RequestSubscribeMessageOption 类型定义错误

### ISSUE THREAD

**Issue by LiJiahaoCoder** [wechat-miniprogram/api-typings#175]
微信订阅消息 _API_ `wx.requestSubscribeMessage` 回调参数类型错误：

```typescript
interface RequestSubscribeMessageOption {
    /** 需要订阅的消息模板的id的集合，一次调用最多可订阅3条消息（注意：iOS客户端7.0.6版本、Android客户端7.0.7版本之后的一次性订阅/长期订阅才支持多个模板消息，iOS客户端7.0.5版本、Android客户端7.0.6版本之前的一次订阅只支持一个模板消息）消息模板id在[微信公众平台(mp.weixin.qq.com)-功能-订阅消息]中配置 */
    tmplIds: any[]
    /** 接口调用结束的回调函数（调用成功、失败都会执行） */
    complete?: RequestSubscribeMessageCompleteCallback
    /** 接口调用失败的回调函数 */
    fail?: RequestSubscribeMessageFailCallback
    /** 接口调用成功的回调函数 */
    success?: RequestSubscribeMessageSuccessCallback
}
```

上述定义导致在回调中获取 `tmplId` 对应的回调状态时导致类型错误，故 `tmplId: any[]`  不如改成 `[tmplId: string]: string`， 如下：

```typescript
interface RequestSubscribeMessageOption {
    [tmplId: string]: string;
    complete?: RequestSubscribeMessageCompleteCallback
    fail?: RequestSubscribeMessageFailCallback
    success?: RequestSubscribeMessageSuccessCallback
}
```

**Comment by SgLy** [comment]
emm，你应该是想说这个定义错了……？
```ts
interface RequestSubscribeMessageSuccessCallbackResult {
    TEMPLATE_ID: string
    errMsg: string
}
```
应该是这样……？
```ts
interface RequestSubscribeMessageSuccessCallbackResult {
    [TEMPLATE_ID: string]: string
    errMsg: string
}
```

**Comment by LiJiahaoCoder** [comment]
> emm，你应该是想说这个定义错了……？
> 
> ```ts
> interface RequestSubscribeMessageSuccessCallbackResult {
>     TEMPLATE_ID: string
>     errMsg: string
> }
> ```
> 
> 应该是这样……？
> 
> ```ts
> interface RequestSubscribeMessageSuccessCallbackResult {
>     [TEMPLATE_ID: string]: string
>     errMsg: string
> }
> ```

是的，不然在 `ts` 中的获取 `callback` 中的 `TEMPLATE_ID` 时会报错。

**Comment by xmsz** [comment]
没错 刚刚也遇到了这个情况
什么时候更新一下

**Comment by Mister-Hope** [comment]
有计划更新么？挺久的了。@SgLy

**Comment by LiJiahaoCoder** [comment]
本想提个 *PR*，然后发现该项目中的这个：

![image](https://user-images.githubusercontent.com/30025543/108036313-06a5a100-7073-11eb-83c6-be0c1a09e979.png)

然后... 所以说这个 *issue* 何时能修一下，不然写着太难受了！
