### ISSUE TITLE
Discussion: Some PR I would like to make

### ISSUE THREAD

**Issue by Mister-Hope** [wechat-miniprogram/api-typings#178]
## First of all, I would like to request opening the discussion panel.

> I thinks putting issues with content like this to discssion panel would be better.

## And I am planning to submit these pr:

- Rewrite Component types to make better support. It may fix #173 and improve #161
- Add more test to the test folder. (I will add a complete type test for `Page` and `Component`)

## And I like to request this changes:

1. Add prettier to this repo and use prettier style (I will also import `eslint-config-prettier` to make sure no conflict with eslint)

**Reason:** 4 space indent make the type files hard to read( especially in complex interface), And prettier do have a better wrap lint behavior.

Before:
![image](https://user-images.githubusercontent.com/33315834/104084146-f0404480-527f-11eb-9da7-2dafa0e9ebc5.png)

After:
![image](https://user-images.githubusercontent.com/33315834/104084152-f7ffe900-527f-11eb-87e8-09d4c244abc5.png)
> I think below is better.

2. Rewrite the whole type test using jest with ts-jest.

We are just using a simple type:

```ts
const expectType: <T>(value: T) => void;
```

Moving to jest can have better test and error output and scope handle(with `describe` and `it`)

3. migrate to github actions.

Reasons: More convenient to open action logs. Besides, visiting travis is slow in China.

I am looking forward your opinion towards the 3 changes above. If you thinks those are fine, I will make PRs

And also I wanna know whether it's possible to add generics in apis (I am not sure if it can be done with auto generation) Related request are #138, #177

**Comment by Mister-Hope** [comment]
![image](https://user-images.githubusercontent.com/33315834/104084537-d5bb9a80-5282-11eb-9f97-932aaabee180.png)
Also I just found a werid thing

**Comment by SgLy** [comment]
1. Rewriting `Component` types or adding tests are always welcomed, feel free to make PRs;
2. Prettier is great, but a tab width of 4 is to meet [DefinitelyTyped's requirement](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes); using [their prettier configuration](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/.prettierrc.json) maybe a better solution;
3. `<T>(value: T) => void` is weaker than the one tsd provided: this only checks if `value` can be assigned to `T`, while tsd's `expectType` checks if the two type are identical. As an example:
    ```ts
    declare const a: any;
    expectType<number>(a)
    ```
    will pass `<T>(value: T) => void` but fails tsd;
4. Tests should have been formatted by eslint. This will be fixed soon.

**Comment by Mister-Hope** [comment]
> Prettier is great, but a tab width of 4 is to meet DefinitelyTyped's requirement; using their prettier configuration maybe a better solution;
> Tests should have been formatted by eslint. This will be fixed soon.
I'll do the jobs by sending PR. I am already working on it.

**Comment by Mister-Hope** [comment]
Just to confirm:
4 spaces in types to met  DefinitelyTyped's requirement and 2 space in test files right?

**Comment by Mister-Hope** [comment]
And what about this one?

> migrate to github actions.
> Reasons: More convenient to open action logs. Besides, visiting travis is slow in China.

**Comment by SgLy** [comment]
> Just to confirm:
> 4 spaces in types to met DefinitelyTyped's requirement and 2 space in test files right?

I prefer to just format test cases using the same configuration with types and made it 4 space indented, for not mixing different tab widths in a single project.



> And what about this one?
> 
> > migrate to github actions.
> > Reasons: More convenient to open action logs. Besides, visiting travis is slow in China.

Migrating to GItHub Actions is also in my plan (but with a low precedence), a PR will be great.
