### ISSUE TITLE
MapContext 类型错误

### ISSUE THREAD

**Issue by somarlyonks** [wechat-miniprogram/api-typings#180]
`MapContext.on`是显然错误的

示例是
```js
MapContext.on('markerClusterCreate', (res) => {})
MapContext.on('markerClusterClick', (res) => {})
```

类型声明里面是
```ts
interface MapContext {
  on (): void
}
```

虽然这个Api本身就有点迷惑，但是类型显然不对也是真的。

还有很多接口在类型声明里面没有，比如`openMapApp`, `removeCustomLayer`, `removeGroundOverlay`, `toScreenLocation`, `updateGroundOverlay`。

**Comment by SgLy** [comment]
收到，`on` 这个我处理一下，其他几个已经有了的，升级一下版本看看？https://github.com/wechat-miniprogram/api-typings/blob/43c0a22/types/wx/lib.wx.api.d.ts#L9602-L9649

**Comment by somarlyonks** [comment]
好的。少的那些我看npm好像`@types/wechat-miniprogram`最新的还是`v3.1.0`。

**Comment by SgLy** [comment]
在 5b107ded984e27ca3f92ad2a0d9f1be85aefee92 和 3.2.3 中修复
