### ISSUE TITLE
Question: observer in props

### ISSUE THREAD

**Issue by Mister-Hope** [wechat-miniprogram/api-typings#183]
https://developers.weixin.qq.com/miniprogram/dev/reference/api/Component.html

![image](https://user-images.githubusercontent.com/33315834/104411148-df0b7680-55a4-11eb-81dc-4e6cef07cd43.png)

Above is which the doc says.

But I fould the test example when rewriting the component test:
https://github.com/wechat-miniprogram/api-typings/blob/384b8d63acf7b804ac8047b6a4e612fc465adab1/test/component.test.ts#L293-L304

Any docs about it?

**Comment by SgLy** [comment]
It's ok but not recommended, thus not appears in doc.

**Comment by SgLy** [comment]
Closing, feel free to reopen if there there are any problems.
