### ISSUE TITLE
SubscriptionsSetting的itemSettings实际上可能为undefined

### ISSUE THREAD

**Issue by xmsz** [wechat-miniprogram/api-typings#185]
`WechatMiniprogram.SubscriptionsSetting`这个接口的字段`itemSettings`，在真实情况下可能是undefined

更具体就是，在调用wx.getSetting接口的时候，如果用户之前不曾点击过订阅消息弹窗的「总是允许」，这个`itemSettings`就是undefined

**Comment by SgLy** [comment]
在 5b107ded984e27ca3f92ad2a0d9f1be85aefee92 和 3.2.3 中修复
