### ISSUE TITLE
offscreenCanvas 没有 width  和 height 么？

### ISSUE THREAD

**Issue by John0King** [wechat-miniprogram/api-typings#189]
根据 MDN 上的介绍， OffscreenCanvas 拥有widht 和height , 但是 你们的文档还有 定义上都没有，
我就好奇了， 这是一张无限大的canvas 么？ 如果绘制超出左侧和顶部边界会被裁切还是保留？

**Comment by SgLy** [comment]
文档的话，具体属性可以参考这个 [RenderingContext 的说明](https://developers.weixin.qq.com/miniprogram/dev/api/canvas/RenderingContext.html)

定义这边因为不能完整引入 `lib.dom.d.ts`，所以要将具体涉及的接口提取合并过来并且保持同步更新，在 #111 跟踪

**Comment by SgLy** [comment]
应该已经在之前的版本里修复了，补充了一个测试用例 a56354e4323c78b6182662e1a89da2e77d4efbba
