### ISSUE TITLE
TypeError: wx.getUserProfile is not a function

### ISSUE THREAD

**Issue by JuliaMakukhina** [wechat-miniprogram/api-typings#196]
I try get user data with wx.getUserProfile which added in last update. But when I have been downloaded actually lib (3.3.0) wx.getUserProfile be undefined
![image](https://user-images.githubusercontent.com/63541585/110687694-daa0ba00-81f1-11eb-8655-ca3ac20500aa.png)

**Comment by Mister-Hope** [comment]
请使用最新的nightly

**Comment by SgLy** [comment]
This repo contains only TypeScript definitions for `wx` interfaces, so installing this lib doesn't help with your issue.

Can you try to get yourself a latest RC Build of `WeChat Devtools` to see if it can resolve this issue? [Download page is here](https://developers.weixin.qq.com/miniprogram/en/dev/devtools/download.html)

**Comment by SgLy** [comment]
Another possible reason is version of Wechat Base Library (baselib), `wx.getUserProfile` requires baselib version >= 2.10.4, check `Details` at the top-right corner, then `Local Settings`, and choose a `Debug Base Library` above 2.10.4 to see if it works.
