### ISSUE TITLE
希望可以添加worker的声明文件

### ISSUE THREAD

**Issue by liziwork** [wechat-miniprogram/api-typings#198]
在主线程里通过wx.createWorker创建的worker是有声明的，但是如果在自己定义的子线程里想使用worker的方法会提示方法不存在。目前解决方法就是自己手动定义一个worker.d.ts的声明文件。
`declare const worker: WechatMiniprogram.Worker`

**Comment by Mister-Hope** [comment]
因为worker原则上只在这一个文件有效，你应该遵循ts的设计理念，在你的子进程文件的头部通过 declare const 声明这个全局常量。

我个人不赞同在声明文件中添加这个变量。

**Comment by liziwork** [comment]
> 因为worker原则上只在这一个~文件~文件夹有效，你应该遵循ts的设计理念，在你的子进程~文件~文件夹里的每个一个文件顶部通过clarify const声明这个变量常量。
> 
> 我个人不反对在声明文件中添加这个变量。它并不是完全可用的。

好像是这么回事，已采纳，谢谢！
