### ISSUE TITLE
Page 的 this 上推导不出自定义的方法

### ISSUE THREAD

**Issue by zhousiyaoyao** [wechat-miniprogram/api-typings#199]
比如在 onShareAppMessage 中 return 了 data 中取出的数据时，this 上取不到 foo 方法。

<img width="244" alt="截屏2021-03-28 下午4 32 07" src="https://user-images.githubusercontent.com/20529133/112746689-240b4a80-8fe3-11eb-8e4d-8b064099faa2.png">

而不从 data 中取值，推导没有问题
<img width="325" alt="截屏2021-03-28 下午4 31 19" src="https://user-images.githubusercontent.com/20529133/112746676-0807a900-8fe3-11eb-9e2f-3e922336300f.png">

**Comment by Mister-Hope** [comment]
See #90 #148.
