### ISSUE TITLE
Missing `wx.arrayBufferToBase64` and `wx.base64ToArrayBuffer` typings.

### ISSUE THREAD

**Issue by malash** [wechat-miniprogram/api-typings#20]
Missing `wx.arrayBufferToBase64` and `wx.base64ToArrayBuffer` typings.

```
2017.03.28
A 新增 mac 版开发工具支持蓝牙调试
A 新增 wx.reLaunch wx.chooseAddress wx.openSetting wx.getClipboardData wx.setClipboardData wx.arrayBufferToBase64 wx.base64ToArrayBuffer wx.showLoading wx.hideLoading wx.startAccelerometer wx.stopAccelerometer wx.onNetworkStatusChange wx.hideShareMenu wx.showShareMenu CanvasContext.setTextAlign 等 API 的调试支持
```

https://developers.weixin.qq.com/miniprogram/dev/devtools/uplog.html#20170328

**Comment by wechat-miniprogram-admin** [comment]
wx.base64ToArrayBuffer and wx.arrayBufferToBase64 are internal interface。

**Comment by malash** [comment]
Alright, I found that [in this issue](https://developers.weixin.qq.com/community/develop/doc/00082479c8cf908deae70a4b151400?highLine=arrayBufferToBase64 ) it said the APIs are deprecated.

So I advice to also deprecate these documents:

https://developers.weixin.qq.com/miniprogram/dev/api/api-util.html
https://open.wechat.com/cgi-bin/newreadtemplate?t=overseas_open/docs/mini-programs/development/api/api-util
