### ISSUE TITLE
wx.getLocation api altitude 属性

### ISSUE THREAD

**Issue by noscripter** [wechat-miniprogram/api-typings#215]
- https://developers.weixin.qq.com/miniprogram/dev/api/location/wx.getLocation.html
`altitude`属性应该是`string | boolean`

**Comment by noscripter** [comment]
![image](https://user-images.githubusercontent.com/1673877/129660119-e509c8ad-5243-4604-a798-cab04cae4784.png)

**Comment by SgLy** [comment]
fixed in npm version 3.4.3
