### ISSUE TITLE
未定义基础库 2.18.0 后新增的部分 API

### ISSUE THREAD

**Issue by fudiwei** [wechat-miniprogram/api-typings#216]
如题。

比如：`wx.stopFaceDetect`、`wx.initFaceDetect`、`wx.faceDetect`、`wx.chooseLicensePlate`、`wx.getChannelsLiveNoticeInfo`、`wx.openChannelsActivity` 等等。

另外 `wx.openChannelsLive` 定义有误，[文档](https://developers.weixin.qq.com/miniprogram/dev/api/open-api/channels/wx.openChannelsLive.html)上的参数是有回调的，但这里没有。

**Comment by SgLy** [comment]
感谢反馈，应该是这两周的文档更新还没同步过来，晚点我更新一版

**Comment by SgLy** [comment]
> 你们是维护文档和维护 Typings 的是两拨人马么……手动从文档仓库里拉取然后构建？
> 
> 这种事情不应该是弄个 git hooks 么，哪怕做不到自动发 PR 更新，最不济也应该给维护者弄个消息提醒啥的么……这每次都得靠人肉识别更新没更新么？😂

都是我们，一言难尽……简单说是不太信任生成结果，发之前会 review，再加上文档更新的频率比较高，所以没做自动化orz（其实是做了，但是没在用）

**Comment by fudiwei** [comment]
> 都是我们，一言难尽……简单说是不太信任生成结果，发之前会 review，再加上文档更新的频率比较高，所以没做自动化orz（其实是做了，但是没在用）

所以我说起码弄个消息提醒也行呀 😂

P.S. 看到 npm 更新了。
