### ISSUE TITLE
[Component] `WxPage` 的定义？

### ISSUE THREAD

**Issue by NewFuture** [wechat-miniprogram/api-typings#22]
https://github.com/wechat-miniprogram/api-typings/blob/f98804cdd7ed1411bd34f658d5fde65d0b98133a/types/wx/lib.wx.component.d.ts#L108

这里`WxPage` 找不定义，是改了Page的声明没有上传 ？

**Comment by wechat-miniprogram-admin** [comment]
WxPage时很早期的写法，后面都改成 Page了。

**Comment by NewFuture** [comment]
> WxPage时很早期的写法，后面都改成 Page了。

所以这里是 `Page.PageInstance` ?
