### ISSUE TITLE
3.4.4 版本的两个问题

### ISSUE THREAD

**Issue by fudiwei** [wechat-miniprogram/api-typings#221]
昨天更新的 3.4.4 版本中：

- 缺失 [wx.showKeyboard](https://developers.weixin.qq.com/minigame/dev/api/device/keyboard/wx.showKeyboard.html) 的接口定义。
- 缺失 [wx.setEnable1v1Chat](https://developers.weixin.qq.com/miniprogram/dev/api/media/voip/wx.setEnable1v1Chat.html) 的接口定义。

其中前者在之前的版本是有定义的，看了 commit log 发现被删除了，请问是什么原因？没看到有公告说此 API 被废弃了。

后者是基础库 1.20.1 的新 API，遗漏了未定义。

**Comment by SgLy** [comment]
- 看了一下，`wx.showKeyboard` 是小游戏接口，如果出现在小程序的定义里的话可能是类型生成有问题；不过我看了一下好像没发现之前有定义？如果有 commit id 的话可以发出来我排查一下
- `wx.setEnable1v1Chat` 3.4.4 我看也是有的，[这里](https://unpkg.com/browse/miniprogram-api-typings@3.4.4/types/wx/lib.wx.api.d.ts#L20954)

**Comment by fudiwei** [comment]
不好意思写错了，是 `wx.searchContacts` 定义被删了 😂

> https://github.com/wechat-miniprogram/api-typings/commit/dd6b9d31b96cbb6a904ebc34869c9a23eb11c649#diff-e7456fac6dcc82bed87bc3d7fe563e2235934285dae9096854b3283306cd3b15L5539

![image](https://user-images.githubusercontent.com/18504146/139901743-0cb70d46-27aa-41f5-99b1-219ae93f667d.png)

---

`setEnable1v1Chat` 是我自己的问题，`1v1` 写成了 `1v1`，误会误会。

**Comment by SgLy** [comment]
文档上没有的接口我们不能保证可用，定义这里和文档保持同步，所以删掉了 `wx.searchContacts`
