### ISSUE TITLE
文档描述与API定义错误

### ISSUE THREAD

**Issue by Mister-Hope** [wechat-miniprogram/api-typings#222]
![image](https://user-images.githubusercontent.com/33315834/142428311-5a1eafb5-b68b-42a5-bc87-fcd5f2e102b5.png)

这里面如果传入 `shortLink`，那么 `appId` 就可以不填了。，所以 `appId` 不是必填项.....

**Comment by Mister-Hope** [comment]
@SgLy

**Comment by TY-LIU** [comment]
哥们借楼问一下，你是如何将自定义参数绑定到 wx上或者是app上。我看了你的这个问题 
Duplicate of #55 ，我目前也有跟你一样的需求，想知道你现在是怎么扩展自定义方法的
类似这样子：
```
// app.ts
import { Event } from './utils/event';
import router  from "./router/router"

wx.router = router;
App({
    event: new Event(),
})

// user.ts
const app = getApp();
Page({
    onLoad() {
        app.event.xxxxx()
    },
    jump(){
        wx.router.xxxxx()
    }
})
```
目前是虽然程序能跑，但是明显不符合规范，而且方法点击也没法跳转。我想扩展声明文件，但是发现声明文件里面namespace没有导出，想知道你怎么实现的

**Comment by SgLy** [comment]
fixed in 3.6.0
