### ISSUE TITLE
不支持文档中的函数

### ISSUE THREAD

**Issue by Zhou-Tx** [wechat-miniprogram/api-typings#223]
![image](https://user-images.githubusercontent.com/54386692/143248961-604cb268-161e-4d90-9d08-16822ca913a4.png)
错误提示：类型“Wx”上不存在属性“onUnhandleRejection”。
使用的基础库版本号为2.21.0
使用的miniprogram-api-typings版本为3.4.4

**Comment by SgLy** [comment]
`wx.onUnhandledRejection` 在 2.10.0 版本就已经有了，是不是拼写不对？

**Comment by Zhou-Tx** [comment]
我已收到你发的邮件，谢谢
