### ISSUE TITLE
behavior的this指向中失去了其兄弟behavior以及所在页面/组件的this属性定义

### ISSUE THREAD

**Issue by dhlolo** [wechat-miniprogram/api-typings#229]
https://github.com/wechat-miniprogram/api-typings/blob/dd6b9d31b96cbb6a904ebc34869c9a23eb11c649/types/wx/lib.wx.behavior.d.ts#L24

这里能不用string吗？用string没法精确提示this的指向

**Comment by SgLy** [comment]
discussed in #230, closing
