### ISSUE TITLE
[Component] SelectorQuery 和 IntersectionObserver 未定义

### ISSUE THREAD

**Issue by NewFuture** [wechat-miniprogram/api-typings#23]
https://github.com/wechat-miniprogram/api-typings/blob/f98804cdd7ed1411bd34f658d5fde65d0b98133a/types/wx/lib.wx.component.d.ts#L79

https://github.com/wechat-miniprogram/api-typings/blob/f98804cdd7ed1411bd34f658d5fde65d0b98133a/types/wx/lib.wx.component.d.ts#L81

这里应该 是 `wx.SelectorQuery `  和  `wx.IntersectionObserver` ？

**Comment by NewFuture** [comment]
发布前可以先ts编译测试一下

**Comment by wechat-miniprogram-admin** [comment]
已补充 component
