### ISSUE TITLE
Missing authorize scope

### ISSUE THREAD

**Issue by Mister-Hope** [wechat-miniprogram/api-typings#231]
See: https://developers.weixin.qq.com/community/develop/doc/000e881c7046a8fa1f4d464105b001?idescene=6

**Comment by Mister-Hope** [comment]
Any update for this @SgLy

**Comment by Mister-Hope** [comment]
Any update? @SgLy

**Comment by SgLy** [comment]
fixed in 3.6.0

**Comment by Mister-Hope** [comment]
腹泻式修复啊你这

**Comment by SgLy** [comment]
太久没更新版本就会变成这样🙃

**Comment by Mister-Hope** [comment]
我 watch 了 repo，好家伙我这邮箱里满屏的你🤣
