### ISSUE TITLE
ButtonGetPhoneNumber接口缺少一个code字段

### ISSUE THREAD

**Issue by TY-LIU** [wechat-miniprogram/api-typings#236]
从基础库 2.21.2 开始，bindgetphonenumber会多返回一个code字段，通过code，后台能够获取到电话号码，前台可以不用wx.login这个api了。
[获取手机号](https://developers.weixin.qq.com/miniprogram/dev/framework/open-ability/getPhoneNumber.html)

**Comment by SgLy** [comment]
#267 中补齐，问题没有解决的话可以重新打开 issue
