### ISSUE TITLE
[cloud] 重复定义 (与lib.es5）

### ISSUE THREAD

**Issue by NewFuture** [wechat-miniprogram/api-typings#24]
https://github.com/wechat-miniprogram/api-typings/blob/f98804cdd7ed1411bd34f658d5fde65d0b98133a/types/wx/lib.wx.cloud.d.ts#L861-L897

这部分声明在`TypeScript`的 `lib.es5`的定义中已经包含这个了

https://github.com/Microsoft/TypeScript/blob/master/lib/lib.es5.d.ts#L1421-L1489

小程序的定义应该是依赖`ES5`(或与ES5共存的)，
这部分不应该再次引入，否在会造成重复定义的问题

**Comment by wechat-miniprogram-admin** [comment]
已去除
