### ISSUE TITLE
wx.hideToast(); option 可选

### ISSUE THREAD

**Issue by Mister-Hope** [wechat-miniprogram/api-typings#245]
![image](https://user-images.githubusercontent.com/33315834/161898229-04fc83a9-b2f8-4186-a63c-d0a467f52562.png)

旧版本通过的代码现在会报错

**Comment by TtTRz** [comment]
3.4.7 将修复

**Comment by anotherso1a** [comment]
什么时候release呀？

**Comment by SgLy** [comment]
带在刚发的 3.5.0 了
