### ISSUE TITLE
缺少wx.decode和wx.encode

### ISSUE THREAD

**Issue by perqin** [wechat-miniprogram/api-typings#247]
文档：[https://developers.weixin.qq.com/minigame/dev/api/util/wx.encode.html](https://developers.weixin.qq.com/minigame/dev/api/util/wx.encode.html)。

**Comment by SgLy** [comment]
小程序中没有提供这两个 API，小游戏定义 [wechat-miniprogram/minigame-api-typings](https://github.com/wechat-miniprogram/minigame-api-typings) 是有的
