### ISSUE TITLE
No onAppRoute Api

### ISSUE THREAD

**Issue by CreazyJack** [wechat-miniprogram/api-typings#248]
The WechatMiniprogram.Wx don't includes  key 'onAppRoute',but when I use wx,it surely has  it and can be used. 
I extend the WechatMiniprogram.WX like this:
<img width="457" alt="image" src="https://user-images.githubusercontent.com/51393413/163113490-ac08e8e7-6f8c-476f-a67b-f3e3c9aa1b55.png">

**Comment by SgLy** [comment]
`wx.onAppRoute` will not be listed in docs or typings since it is not a public API. Non-public API may be changed or removed at any time without prior notice, use it on your own risk. For typings, extend it like the way you shown might be a good choice.
