### ISSUE TITLE
wx.getSystemInfoSync().platform 类型缺失

### ISSUE THREAD

**Issue by zhang704** [wechat-miniprogram/api-typings#249]
platform: 'ios' | 'android' | 'windows' | 'mac'

在开发工具下应该为'devtools'
<img width="249" alt="image" src="https://user-images.githubusercontent.com/18161513/163310248-fe60d650-120e-4b04-80de-494ac4bad290.png">

**Comment by SgLy** [comment]
3.6.0 已修复
