### ISSUE TITLE
Cannot augment module 'wx' with value exports

### ISSUE THREAD

**Issue by Pasoul** [wechat-miniprogram/api-typings#25]
报错如下：

`node_modules/miniprogram-api-typings/types/wx/lib.wx.cloud.d.ts(202,19): error TS2649: Cannot augment module 'wx' with value exports because it resolves to a non-module entity`

版本：
^2.6.5-1

**Comment by fishen** [comment]
+1

**Comment by NewFuture** [comment]
这个地方去掉了 `cloud`的定义 https://github.com/MS-DG/api-typings
可以先用这个版本试试

**Comment by YikaJ** [comment]
重复 declare namespace wx 了

**Comment by lili21** [comment]
any update?

**Comment by wechat-miniprogram-admin** [comment]
fixed in 2.7.7
