### ISSUE TITLE
是否可以增加async的支持

### ISSUE THREAD

**Issue by yekai9527** [wechat-miniprogram/api-typings#251]
`onLoad:async ()=>{},
`
在页面或者组件构造器中,函数前面增加async会提示错误

TS2705: An async function or method in ES5/ES3 requires the 'Promise' constructor. Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your '--lib' option.

**Comment by Mister-Hope** [comment]
这是你自己tsconfig的问题...

**Comment by yekai9527** [comment]
感谢感谢 已经解决 再次感谢

**Comment by SgLy** [comment]
已经解决就先关闭了，还有问题的话再打开
