### ISSUE TITLE
类型“Wx”上不存在属性“openCustomerServiceChat”

### ISSUE THREAD

**Issue by chuoke** [wechat-miniprogram/api-typings#255]
版本：   '@types/wechat-miniprogram': ^3.4.1

**Comment by SgLy** [comment]
3.4.2 版本加入的，升级一下版本看看？
https://github.com/wechat-miniprogram/api-typings/commit/eebdc03e03cafde2cd4598891311c00386032d3f#diff-e7456fac6dcc82bed87bc3d7fe563e2235934285dae9096854b3283306cd3b15R17735
