### ISSUE TITLE
interface VKSession落后文档太多

### ISSUE THREAD

**Issue by werts** [wechat-miniprogram/api-typings#257]
VKSession在类型定义里几乎没有，就只有几个方法，根本用不了
![image](https://user-images.githubusercontent.com/13898404/175506026-fd4975f8-e52e-4407-872b-4dd4154ca626.png)
![image](https://user-images.githubusercontent.com/13898404/175505898-aac43675-a4f5-4e63-8ec0-202446d28074.png)

**Comment by SgLy** [comment]
上周发的 3.6.0 应该更新到和文档一致了，现在还有哪些缺少吗？
