### ISSUE TITLE
wxs definitions[wxs 的定义声明]

### ISSUE THREAD

**Issue by NewFuture** [wechat-miniprogram/api-typings#26]
创建了 [@types/miniprogram-wxs](https://www.npmjs.com/package/@types/miniprogram-wxs
) 声明`wxs`定义npm的包

把 @wechat-miniprogram-admin 添加到了[maintainer list](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/584682b746557368e8adb3339ac973bd7da03740/types/miniprogram-wxs/index.d.ts#L4)里了 ，如果有必要官方可以直接更新这个包

> 定义 WXS 文件可以直接声明引用 `miniprogram-wxs`
```ts

/// <reference types="miniprogram-wxs"/>

//  write typescript code as wxs
const today: Date = getDate();
// javascript code as wxs
var today = getDate();
```

源文件: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/miniprogram-wxs

**Comment by SgLy** [comment]
[文档](https://developers.weixin.qq.com/miniprogram/dev/framework/view/wxs/) 中有提到：
> WXS 与 JavaScript 是不同的语言，有自己的语法，并不和 JavaScript 一致。

用 ts 编译到 js 来作为 wxs 的话，是有可能无法正常运行的，所以我们暂时不会做这套定义~

**Comment by Mister-Hope** [comment]
......
