### ISSUE TITLE
SceneValues 不全

### ISSUE THREAD

**Issue by kejiweixun** [wechat-miniprogram/api-typings#269]
[文档的场景值](https://developers.weixin.qq.com/miniprogram/dev/reference/scene-list.html)和类型声明中的 [SceneValues](https://github.com/wechat-miniprogram/api-typings/blob/b9c51b72e4f36e1d1fb5c10c5c87cdd63f615b5d/types/wx/lib.wx.app.d.ts#L40) 不同，文档中很多场景值在类型声明中没有。

**Comment by SgLy** [comment]
3.8.1 中补齐，还有问题的话可以重新打开 issue
