### ISSUE TITLE
[component] methods 参数限制

### ISSUE THREAD

**Issue by NewFuture** [wechat-miniprogram/api-typings#27]
component 定义不错，但是有些小BUG

https://github.com/wechat-miniprogram/api-typings/blob/4593cb088077d983297ef298054ef5954d767535/types/wx/lib.wx.component.d.ts#L176

这里的`methods`参数不一定为空，应该是任意的

**Comment by wechat-miniprogram-admin** [comment]
fixed in 2.7.7-1
