### ISSUE TITLE
[component] properties

### ISSUE THREAD

**Issue by NewFuture** [wechat-miniprogram/api-typings#28]
1. 不支持缩写形式?
```js
{
  properties:{
    key:Boolean // 直接指明类型
  }
}
```
2.  `optionalTypes` 为可选属性 ?

https://github.com/wechat-miniprogram/api-typings/blob/4593cb088077d983297ef298054ef5954d767535/types/wx/lib.wx.component.d.ts#L40

3. properties 和 data 在`BaseComponent`中声明了，不用再在继承的 `WxComponent`重新定义了

https://github.com/wechat-miniprogram/api-typings/blob/4593cb088077d983297ef298054ef5954d767535/types/wx/lib.wx.component.d.ts#L68-L73

https://github.com/wechat-miniprogram/api-typings/blob/4593cb088077d983297ef298054ef5954d767535/types/wx/lib.wx.component.d.ts#L165-L171

**Comment by NidMo** [comment]
我尝试用ts写一些自定义组件，然后那个组件的ts就报错了
![image](https://user-images.githubusercontent.com/24955673/56333170-a834e080-61c5-11e9-9357-97ad37707a10.png)
代码如上
![image](https://user-images.githubusercontent.com/24955673/56333189-b97ded00-61c5-11e9-8727-cff486ba239a.png)
报错信息如上，是我写的方式不对吗？

**Comment by NewFuture** [comment]
@NidMo 可以先试试这个https://github.com/MS-DG/api-typings

**Comment by NidMo** [comment]
> @NidMo 可以先试试这个https://github.com/MS-DG/api-typings

大佬，这个是你个人维护的？

**Comment by NewFuture** [comment]
> 大佬，这个是你个人维护的？

不完全是，这个项目有一个team (@ms-dg) 在支持。
在官方完善稳定和加入types之前(目前看短期是不可能了)，这个项目会一直维护，并保持和微信的的兼容

**Comment by NidMo** [comment]
> > 大佬，这个是你个人维护的？
> 
> 不完全是，这个项目有一个team (@MS-DG) 在支持。
> 在官方完善稳定和加入types之前(目前看短期是不可能了)，这个项目会一直维护，并保持和微信的的兼容

估计离官方稳定还有一段遥远的路程，辛苦你了大佬

**Comment by NewFuture** [comment]
@NidMo 欢迎PR

**Comment by godbasin** [comment]
![image](https://user-images.githubusercontent.com/11885123/56416749-5d4dc280-62c4-11e9-8228-f30b66679a1b.png)
`optionalTypes`漏了个问号

**Comment by NewFuture** [comment]
> `optionalTypes`漏了个问号

@godbasin  是的，看这个commit
https://github.com/MS-DG/api-typings/commit/caf66a5fb298a3478b4251fbff9095744adc3396

**Comment by listenzz** [comment]
关于第三点，重新定义还是有必要的，因为去掉了 ！号

**Comment by NewFuture** [comment]
All fixed in https://github.com/MS-DG/api-typings

here is a test example https://github.com/MS-DG/api-typings/blob/master/test/componet.test.ts

**Comment by wechat-miniprogram-admin** [comment]
fixed in 2.7.7-1
