### ISSUE TITLE
[开发者工具]无法更新声明文件，总是提示“声明文件更新失败，或者无需更新”

### ISSUE THREAD

**Issue by xiaweiss** [wechat-miniprogram/api-typings#290]
如题，开发者工具版本 mac arm Nightly 1.06.230622

**Comment by Mister-Hope** [comment]
我认为这类问题你应该投到社区 https://developers.weixin.qq.com/community/develop/mixflow?source=indexnew

**Comment by xiaweiss** [comment]
@Mister-Hope 声明文件相关的问题，投到这里是合适的。社区更适合综合问题

**Comment by Mister-Hope** [comment]
? 这里跟工具有什么关系

**Comment by xiaweiss** [comment]
声明文件最终要在工具使用的，工具也算是一个安装方式

**Comment by Mister-Hope** [comment]
？ 工具的安装方式是在这个仓库写的？是不是你电脑装了QQ装不上你要去给微软发bug单，因为windows也是QQ的一个运行环境？

**Comment by xiaweiss** [comment]
好的，我去找开发者工具的同事反应，不争论这个问题了。谢谢

**Comment by Mister-Hope** [comment]
我在多解释一句，这个仓库只有 @SgLy  一个人在维护和同步定义，而且每次更改都会以 `miniprogram-api-typings` 发新版，工具不能把这个包的内容成功拉到本地是它的问题，你提到这个仓库不会有人管的。

**Comment by xiaweiss** [comment]
好的，了解。这个也不是什么大问题，手动复制粘贴、或者安装包也能解决，谢谢你回复。
