### ISSUE TITLE
@types/wechat-miniprogram 还计划维护吗？

### ISSUE THREAD

**Issue by yangmingshan** [wechat-miniprogram/api-typings#298]
@types/wechat-miniprogram 已经超过一年未更新了，如果不再维护了，建议说明一下并从 README 中拿掉。

**Comment by xiaweiss** [comment]
相关问题 #270，小程序 api 更新很快，包括最近的 skyline 的特性。开发者工具目前也无法更新声明文件。
建议是用 miniprogram-api-typings 或者 miniprogram-type 用三斜线语法引入
