### ISSUE TITLE
`this.renderer` 缺乏类型定义

### ISSUE THREAD

**Issue by yangmingshan** [wechat-miniprogram/api-typings#302]
`Page` 和 `Component` 的实例都新增了 `renderer` 属性，其值为 `webview` 或 `skyline`

https://developers.weixin.qq.com/miniprogram/dev/framework/runtime/skyline/migration/compatibility.html#:~:text=%E6%94%AF%E6%8C%81%E4%B8%8E%E5%B7%AE%E5%BC%82-,%E6%A0%B9%E6%8D%AE%E4%B8%8D%E5%90%8C%20renderer%20%E5%85%BC%E5%AE%B9,-%E6%9C%89%E6%97%B6%EF%BC%8C%E5%8D%95%E7%BA%AF%E7%94%A8

**Comment by xiaweiss** [comment]
@yangmingshan hi, fixed in here https://github.com/xiaweiss/miniprogram-type/issues/4
