### ISSUE TITLE
[bug] 3.11.0 版本 WechatMiniprogram.Err 丢失了

### ISSUE THREAD

**Issue by xiaweiss** [wechat-miniprogram/api-typings#307]
看代码变更为 WechatMiniprogram.ExceptionReason，是否要考虑向前兼容？

see https://github.com/xiaweiss/miniprogram-type/issues/3

**Comment by Mister-Hope** [comment]
这个库从来就没考虑过向前兼容，类似的改动已经有很多次了，你自己调整一下吧....

**Comment by xiaweiss** [comment]
@Mister-Hope 希望 API 废弃了，至少有个变更记录吧。腾讯也是大厂了，希望能严谨一些

**Comment by Mister-Hope** [comment]
问题就在于这里面很多文件都是自动生成的。

**Comment by Mister-Hope** [comment]
我不是主要维护者，你可以问问@SgLy 
这个问题

**Comment by xiaweiss** [comment]
好的，感谢解答

**Comment by SgLy** [comment]
看起来应该是被变更到了 `RequestFailCallbackErr`，原因是新的 `requestVirtualPayment` 接口也加入了一个 `Err` 类型， 导致命名冲突，新的被命名为 `RequestVirtualPaymentFailCallbackErr`。这个自动命名和命名冲突的问题受限于我们当前文档的组织方式，实际上对 TS 并不太友好，短期内可能难以解决，只能通过减少直接引用某个类型，更多依赖自动推导来回避。

**Comment by xiaweiss** [comment]
以上回复不是针对个人哈，写个 CHANGELOG 完全不是技术问题，是个是否重视的问题。

既然这边是自动生成的，那么把相关改动信息同步过来写到这边的 CHANGELOG，实在不行写到小程序基础库更新日志会好些。

但搞不好不是 api-typing 的工作范围吧，即便有社区的贡献者也无能为力，最终结果就是 **开发者体验差**。

这个问题涉及到小程序生态中，各方协作的问题，腾讯内部工作流程的问题，以及是否关注开发者体验的问题。

关于短期内可能难以解决，我理解如果不是哪个领导有决心提高开发者体验，靠基层员工也是彻底无法解决的。
