### ISSUE TITLE
[Component]behaviors拓展

### ISSUE THREAD

**Issue by godbasin** [wechat-miniprogram/api-typings#31]
自定义组件支持拓展`behaviors`，见[自定义组件扩展](https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/extend.html)。

拓展以后可能会新增属性，如官方的`computed`:
```
const beh = require('./behavior.js')
Component({
  behaviors: [beh],
  data: {
    a: 0,
  },
  computed: {
    b() {
      return this.data.a + 100
    },
  },
  methods: {
    onTap() {
      this.setData({
        a: ++this.data.a,
      })
    }
  }
})
```
此时会报错。

**Comment by wechat-miniprogram-admin** [comment]
`behaviors` 是很自由的东西，用 `behaviors` 增加或改了东西之后，原来的定义肯定是不能兼顾的。可以试着重写一下定义，[这个例子](https://github.com/wechat-miniprogram/api-typings/blob/master/test/computed.test.ts) 尝试解决了 computed，可以参考一下？
