### ISSUE TITLE
[cloud]依赖安装后报错

### ISSUE THREAD

**Issue by godbasin** [wechat-miniprogram/api-typings#32]
版本号：`npm install miniprogram-api-typings@2.6.5-2`
![image](https://user-images.githubusercontent.com/11885123/56417305-0d6ffb00-62c6-11e9-81d9-375a0cc3a240.png)

**Comment by pyu10055** [comment]
I have the same error, please fix

**Comment by yanxlg** [comment]
同样的问题，不可用

**Comment by wechat-miniprogram-admin** [comment]
fixed in 2.7.7
