### ISSUE TITLE
addCard中cardExt参数类型错误

### ISSUE THREAD

**Issue by evannalikeyou** [wechat-miniprogram/api-typings#34]
文档描述为：“需进行 JSON 序列化为字符串传入”
然而声明的是一个对象

![image](https://user-images.githubusercontent.com/8686685/56675372-7d2f1d00-66ee-11e9-9f20-2d2ec6a5f144.png)

**Comment by wechat-miniprogram-admin** [comment]
2.7.5 tag 修复
