### ISSUE TITLE
wx.chooseMessageFile返回结果参数类型错误

### ISSUE THREAD

**Issue by techGay** [wechat-miniprogram/api-typings#35]
interface ChooseMessageFileSuccessCallbackResult {
    /** 返回选择的文件的本地临时文件对象数组 */
    tempFiles: ChooseFile;
  }

### 应该是返回的ChooseFile数组

  interface ChooseMessageFileSuccessCallbackResult {
    /** 返回选择的文件的本地临时文件对象数组 */
    tempFiles: ChooseFile[];
  }

**Comment by NewFuture** [comment]
it has been fixed here MS-DG/api-typings#2

**Comment by wechat-miniprogram-admin** [comment]
fixed in 2.7.7
