### ISSUE TITLE
该类型定义文件是否支持企业微信的 JS-SDK?

### ISSUE THREAD

**Issue by nyaapass** [wechat-miniprogram/api-typings#37]
[企业微信的 JD-SDK](https://work.weixin.qq.com/api/doc#90001/90144/90547) 里有很多 API 看上去似乎和小程序的一模一样. 请问这些相同的 API 是否可以使用该类型定义文件? 会不会存在虽然 API 名称一致, 但是两者的输入输出类型完全不一样的情况呢?

**Comment by wechat-miniprogram-admin** [comment]
很多接口是类似的，但是两个团队维护的，可能会有不一致的情况
