### ISSUE TITLE
[Page]selectComponent未定义?

### ISSUE THREAD

**Issue by ascend13** [wechat-miniprogram/api-typings#40]
![TIM图片20190528173506](https://user-images.githubusercontent.com/25900057/58467871-095db580-816f-11e9-8671-68891b909e1b.png)

**Comment by yuangu** [comment]
我现在用// @ts-ignore 来屏蔽错误是可以的。https://www.jianshu.com/p/9dcbfe44585c

**Comment by wechat-miniprogram-admin** [comment]
fixed in 2.7.7-1
