### ISSUE TITLE
CanvasContext 的 lineCap 和 lineJoin 类型错误

### ISSUE THREAD

**Issue by nyaapass** [wechat-miniprogram/api-typings#41]
- [lib.wx.api.d.ts#L375](https://github.com/wechat-miniprogram/api-typings/blob/master/types/wx/lib.wx.api.d.ts#L375) 中 `lineCap` 属性应为 `'butt' | 'round' | 'square'` 而不是 `number`
- [lib.wx.api.d.ts#L383](https://github.com/wechat-miniprogram/api-typings/blob/master/types/wx/lib.wx.api.d.ts#L383) 中 `lineJoin` 属性应为 `'bevel' | 'round' | 'miter'` 而不是 `number`

**Comment by wechat-miniprogram-admin** [comment]
2.7.5 tag 修复
