### ISSUE TITLE
类型“Wx”上不存在属性“cloud”。

### ISSUE THREAD

**Issue by baranwang** [wechat-miniprogram/api-typings#42]
在 vscode 中好像并没有加载出来 wx.cloud 会提示

>  类型“Wx”上不存在属性“cloud”。

**Comment by wechat-miniprogram-admin** [comment]
fixed in 2.7.7

**Comment by flippancy** [comment]
2.10.1的版本还是有这个问题

**Comment by flippancy** [comment]
> 2.10.1的版本还是有这个问题

![image](https://user-images.githubusercontent.com/6467703/75000495-6f2a6400-5499-11ea-86df-4ffb444f23d1.png)
