### ISSUE TITLE
wx canvasGetImageData 成功回调参数类型错误

### ISSUE THREAD

**Issue by z-ao** [wechat-miniprogram/api-typings#43]
lib.wx.api.d.ts#L11258
type CanvasGetImageDataSuccessCallback应该是三个参数
width: number,
height: number,
data: Uint8ClampedArray

而不是
result: CanvasGetImageDataSuccessCallbackResult,
data: Uint8ClampedArray,

**Comment by wechat-miniprogram-admin** [comment]
fixed in 2.7.7
