### ISSUE TITLE
WechatMiniprogram未定义？

### ISSUE THREAD

**Issue by GodofHope** [wechat-miniprogram/api-typings#44]
在整个项目中找不到namespace WechatMiniprogram

**Comment by GodofHope** [comment]
同时还有错误：Cannot find name 'IAnyObject'.

**Comment by GodofHope** [comment]
所以直接引入报错的原因是什么？我报了一排的wx is not defined的错误。我把type文件拷到我自己声明的@types才好了一些...

**Comment by wechat-miniprogram-admin** [comment]
因为是一个纯定义的包，但是不在 `DefinitelyTyped` 里，所以 ts 编译器可能找不到定义文件。目前也没有特别好的解决方法，可以在项目合适的位置建一个 `index.d.ts`，用三斜杠去引用：

```typescript
/// <reference path="../node_modules/miniprogram-api-typings/index.d.ts" />
```

**Comment by NewFuture** [comment]
所以是否考虑加入`@types` 里？  #7 
这个之前我PR过一个版本，https://github.com/DefinitelyTyped/DefinitelyTyped/pull/34081
除了一些文档注释的格式等小问题，主要存一个block问题是接口命名的问题

**Comment by IceApriler** [comment]
这个问题，是否可以通过在`tsconfig.json`里面设置`typeRoots`来解决？
```
"typeRoots": [
      "node_modules/@types",
      "node_modules/miniprogram-api-typings"
    ]
```
我这样做是好使的，可以参考一下。

https://github.com/qingyangkeji/mini-app-skeleton/tree/ts

**Comment by NewFuture** [comment]
@IceApriler 修改ts配置的话 最好用 `types`  ( typesRoots 是指 定义的 搜索目录)

```json
    
{
    "compilerOptions": {
        "types": ["miniprogram-api-typings"],
    }
}
```
reference https://github.com/NewFuture/miniprogram-template/blob/master/tsconfig.json#L35


现在这个npm定义需要修改`tsconfig`, 不能零配置使用

**Comment by IceApriler** [comment]
@NewFuture 

If `types` is specified, only packages listed will be included. For instance:
```
{
   "compilerOptions": {
       "types" : ["node", "lodash", "express"]
   }
}
```
This `tsconfig.json` file will only include `./node_modules/@types/node`, `./node_modules/@types/lodash` and `./node_modules/@types/express`. Other packages under `node_modules/@types/*` will not be included.

🤔文档说这个是用来限制自动引入`@types`下的定义的。

**Comment by NewFuture** [comment]
> ```
> 
> }
> ```
> 
> 
> This `tsconfig.json` file will only include `./node_modules/@types/node`, `./node_modules/@types/lodash` and `./node_modules/@types/express`. Other packages under `node_modules/@types/*` will not be included.
> 
> 
> 🤔文档说这个是用来限制自动引入`@types`下的定义的。

关闭自动引入，是指定types时ts的另一个行为(不能说就是用来干这个的)，
这个在安装了一些其它工具时(比如 prettier/eslint)很有用, 可以屏蔽一些这种引入的不需要的types提示(比如node的)


可以用ts生成带定义的 `.d.ts`文件可以看出 types 和 typeRoots区别

**Comment by GodofHope** [comment]
对的，第一个是能否添加到@types里，如果不能能否完善一下文档？
我觉得不是所有人都十分了解d.ts声明文件

**Comment by wechat-miniprogram-admin** [comment]
暂时不会加到 `@types` 中，后续是否加入等稳定后再讨论。之后会加入简单的使用方法。

**Comment by yoyo837** [comment]
如今, 可以再重新讨论这个问题了吗?

**Comment by SgLy** [comment]
> 如今, 可以再重新讨论这个问题了吗?

@yoyo837 如果是指 `@types` 的问题的话，现在已经有了，详细可以看看 README

**Comment by yoyo837** [comment]
我使用的 `在 tsconfig.json 中指定 types: ["miniprogram-api-typings"]`, 仍然有`WechatMiniprogram`是`no-undef`的eslint

**Comment by SgLy** [comment]
按照 typescript-eslint/typescript-eslint#2799 和 [这个 FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/main/docs/linting/TROUBLESHOOTING.md#i-get-errors-from-the-no-undef-rule-about-global-variables-not-being-defined-even-though-there-are-no-typescript-errors) 来看，eslint 应该是建议 ts 下直接关掉 `no-undef` 的

**Comment by yoyo837** [comment]
OK,  那有计划打算支持type 模块化吗?

**Comment by SgLy** [comment]
type 模块化是指……？
