### ISSUE TITLE
wx.navigateBack(Object object)的改进？

### ISSUE THREAD

**Issue by GodofHope** [wechat-miniprogram/api-typings#48]
很多api其实都存在这个问题，这个也基本上是一个文档的问题.....
我以wx.navigateBack这个API举例说明吧....

文档中说`delta`是必填项，也就是说，如果我想要单纯做一个返回，我应该`wx.navigateBack({delta:1)`。

但是返回上一页的逻辑是如此的常用，以至于这个api实际上从我所入坑的1.2.几版本，delta其实就是一个可选参数，或者说这个api本来就可以不传入对象，`wx.navigateBack()`的调用结果一直都是返回上一页，根本不会报错....

所以我相信不止我一个开发者会大量的写`wx.navigateBack()`这种调用形式.....而在TS里就会报错，我每次都是手动把`delta:number`这类改成`delta?:number`。

再举一种例子，同理类似的API还有`wx.setTabBarStyle`,`wx.setBackgroundColor`,`setNavigationBarColor`这三货。
这三个API的参数很多都是必填，但是开发中会经常遇到就想改特定的某一项，这个时候只传这一项实际上是完全OK的，根本不需要把其他必填的参数都按照原来的再传一遍......

所以请求可不可以把实际上可以省略的这种通用api的调用也给改一下呢？

**Comment by wechat-miniprogram-admin** [comment]
本质问题应该是 `delta` 实际上不必须，这个确认过之后再跟文档一起修吧
