### ISSUE TITLE
命名规则和版本?

### ISSUE THREAD

**Issue by NewFuture** [wechat-miniprogram/api-typings#49]
最近更新的2.7.x 修改了`namespace`，这是一个完全的break change.
已经和2.6.x以及之前的 完全不兼容了,甚至导致一些项目build break,(从版本上将完全是两个大版本的变化)。

这种namespace以及interface名称是不是应该有个确定规则?(而不是随意更改)

另外对于break change 能否应该提供一下changelog?

**Comment by wechat-miniprogram-admin** [comment]
最新版本重写的主要目的是提供更准确、更全面的定义（而不是像之前某个 issue 里说的那样糊弄），所以除了重写以外，同时也修改了原来不是很规范的 namespace 和类型的命名。如无意外，这些名称不会再随意变化，除非因需要增删特性或修复 bug 等而不得已需要修改。

对于这次 breaking change 没有及时提供 changelog 十分抱歉，以后会逐步提供 changelog 和基本的使用说明。项目正在逐渐起步，非常感谢一直以来的关注～

**Comment by NewFuture** [comment]
1. 既然是重写的又重命名了,能把否把命名规则符合 DefinitelyTyped 的规则(如 IAnyObject) https://github.com/DefinitelyTyped/DefinitelyTyped#lint
2. 基于 dtslint 添加类型推断测试的testcase  以保证每次发布的都是能正常编译

**Comment by wechat-miniprogram-admin** [comment]
接下来会逐步添加 test 和 lint 的
