### ISSUE TITLE
新版本没有declare namespace wx ?

### ISSUE THREAD

**Issue by IceApriler** [wechat-miniprogram/api-typings#50]
使用了最新的2.7.7-1，lib.wx.api.d里面的wx不见了，这样搞还能用吗，没有类型提示了。

**Comment by IceApriler** [comment]
将 `userInfoReadyCallback?(res: wx.UserInfo): void` 修改成了 `userInfoReadyCallback?(res: WechatMiniprogram.UserInfo): void`，现在的ts模板还没有修改过来，😳。

**Comment by nyaapass** [comment]
本来 `wx` 用的好好的, 在没有任何说明的情况下就突然变成了 `WechatMiniprogram`. 

希望官方能在更新的时候提供 change log

**Comment by wechat-miniprogram-admin** [comment]
对于这次 breaking change 没有及时提供 changelog 十分抱歉，以后会逐步提供 changelog 和基本的使用说明～

**Comment by GodofHope** [comment]
> 对于这次 breaking change 没有及时提供 changelog 十分抱歉，以后会逐步提供 changelog 和基本的使用说明～

这个是很有必要的，另外我不额外开PR了，麻烦问一下2.8.0什么时候出啊，这些应该会再2.8.0修复吧？我就先不更新这个版本了？

**Comment by wechat-miniprogram-admin** [comment]
> 这个是很有必要的，另外我不额外开iSSue了，麻烦问一下2.8.0什么时候出啊，这些应该会再2.8.0修复吧？我就先不更新这个版本了？

API 的类型定义和文档是同步的，标记 `fix in next version` 的 issue 会跟着 2.8.0 一起修

**Comment by NidMo** [comment]
为什么突然把命名空间从wx改成WechatMiniprogram。WechatMiniprogram这个名字会长时间使用下去？还有为什么把名字改成这么长？
