### ISSUE TITLE
新版本没有了PageInstance，this成any了

### ISSUE THREAD

**Issue by IceApriler** [wechat-miniprogram/api-typings#52]
是我用法不对，还是typings支持度不够？

**Comment by wechat-miniprogram-admin** [comment]
新版本重写了 page 的定义文件，有些接口的名称发生了变化可能有影响。可以给一个 this 推导出 any 的例子看看吗？

**Comment by IceApriler** [comment]
以下这些this都没有：

https://github.com/qingyangkeji/mini-app-skeleton/blob/90df7243b922a10f54217e3e57b4b2fa44e3cebe/src/app.ts#L31

https://github.com/qingyangkeji/mini-app-skeleton/blob/90df7243b922a10f54217e3e57b4b2fa44e3cebe/src/pages/index/index.ts#L29

**Comment by wechat-miniprogram-admin** [comment]
这里这两个 `this` 都能正常推导的，检查一下你的编译选项中 `noImplicitAny` 打开了没有

**Comment by IceApriler** [comment]
是开了的。

https://github.com/qingyangkeji/mini-app-skeleton/blob/90df7243b922a10f54217e3e57b4b2fa44e3cebe/tsconfig.json#L9

以下代码是工具给的模板里的。

```ts
//app.ts
export interface IMyApp {
  userInfoReadyCallback?(res: WechatMiniprogram.UserInfo): void
  globalData: {
    userInfo?: WechatMiniprogram.UserInfo
  }
}

App<IMyApp>({
  onLaunch() {
    // 展示本地存储能力
    var logs: number[] = wx.getStorageSync('logs') || []
    logs.unshift(Date.now())
    wx.setStorageSync('logs', logs)

    // 登录
    wx.login({
      success(_res) {
        // console.log(_res.code)
        // 发送 _res.code 到后台换取 openId, sessionKey, unionId
      }
    })
    // 获取用户信息
    wx.getSetting({
      success: (res) => {
        if (res.authSetting['scope.userInfo']) {
          // 已经授权，可以直接调用 getUserInfo 获取头像昵称，不会弹框
          wx.getUserInfo({
            success: res => {
              // 可以将 res 发送给后台解码出 unionId
              this.globalData.userInfo = res.userInfo
              // 由于 getUserInfo 是网络请求，可能会在 Page.onLoad 之后才返回
              // 所以此处加入 callback 以防止这种情况
              if (this.userInfoReadyCallback) {
                this.userInfoReadyCallback(res.userInfo)
              }
            }
          })
        }
      }
    })
  },
  globalData: {
  }
})
```
你说这里的this可以正常推导，是亲自跑过代码了还是感觉可以推导？

wx可以正常提示。
![image](https://user-images.githubusercontent.com/29689307/62759820-ff342d80-bab4-11e9-8bc9-e4c78e63ec32.png)

this不可以。
![image](https://user-images.githubusercontent.com/29689307/62759813-f9d6e300-bab4-11e9-99d4-f5f5e539ab9b.png)

**Comment by wechat-miniprogram-admin** [comment]
`tsconfig.json` 中加入`"strict": true`

**Comment by IceApriler** [comment]
好使了，根据你的提示，我又详细试了试，发现只要开启`noImplicitThis`就好使，不知道为啥🤔。
