### ISSUE TITLE
为何不将命名空间下的interface export出去？

### ISSUE THREAD

**Issue by loveholly** [wechat-miniprogram/api-typings#53]
为何不将命名空间下的interface export出去？如果我现在要使用某个interface去描述某个回调参数的类型好像只能通过命名空间来访问，例如：

```ts
export interface IMyApp {
  userInfoReadyCallback?(res: WechatMiniprogram.UserInfo): void
  globalData: {
    userInfo?: WechatMiniprogram.UserInfo
  }
  onDataChange: () => void
}
```

上面代码中的`UserInfo`需要通过`WechatMiniprogram`命名空间访问，个人觉得比较啰嗦

而且比较奇怪的是整个库并没有被当做一个module来使用，如果是按照module的方式去实现，应该无须担心命名冲突的问题了吧。

**Comment by wechat-miniprogram-admin** [comment]
`declare namespace` 下的 interface 是否 export 应该没有影响？

如果用 `declare module "WechatMiniprogram"`，import 应该是会被编译成 require 的，而实际上框架接口是不需要 require 的

**Comment by xmsz** [comment]
为啥现在还没改成module的方式，命名空间这种用户在后面版本越来越多坑
例如现在eslint@7.9.0 + typescript@4.0.3 直接疯狂报错not-ref

最大问题是，报这个错还好，普通情况我们就自己引用一次type，但是namespace没办法直接引用... 太麻烦了

**Comment by SgLy** [comment]
@xmsz 不用 module 的原因我觉得之前的回复应该还挺清楚的…… 我看了一下，测试现在是在 ts@3.9.7 + eslint@7.9.0 下跑的，试了一下 ts@4.0.3 也能正常通过，再具体看一下是哪个配置导致报错？namespace 引用是指想直接引用 namespace 里的内容吗？

**Comment by xmsz** [comment]
> @xmsz 不用 module 的原因我觉得之前的回复应该还挺清楚的…… 我看了一下，测试现在是在 ts@3.9.7 + eslint@7.9.0 下跑的，试了一下 ts@4.0.3 也能正常通过，再具体看一下是哪个配置导致报错？namespace 引用是指想直接引用 namespace 里的内容吗？

试试
```
  "devDependencies": {
    "@types/wechat-miniprogram": "3.0.0",
    "@typescript-eslint/parser": "^4.2.0",
    "eslint": "7.9.0",
    "eslint-config-airbnb-base": "14.2.0",
    "eslint-plugin-import": "^2.22.1",
    "typescript": "^4.0.3",
    "vue-eslint-parser": "^7.1.0"
  }
```
```
module.exports = {
  root: true,
  env: {
    es6: true,
  },
  extends: ['airbnb-base'],
  parser: 'vue-eslint-parser',
  parserOptions: {
    parser: '@typescript-eslint/parser',
  },
};
```
```
const a: WechatMiniprogram.AccessCompleteCallback | null = null;
console.log(a);
```

![image](https://user-images.githubusercontent.com/5879146/94711362-9d9ae680-037a-11eb-9e1d-3421616981f2.png)

不过是什么插件造成的，主要是现在没有备选方案，没有必要搞得太死

那么多type没出问题 也必要鹤立独行
