### ISSUE TITLE
新版typings的setData可否支持泛型？

### ISSUE THREAD

**Issue by loveholly** [wechat-miniprogram/api-typings#54]
最新版里面的`setData`方法类型声明里面引用了一个`IAnyObject`类型，导致我在组件或者page里面使用setData的时候无法获知准确的类型。

建议让其支持泛型：
![image](https://user-images.githubusercontent.com/5133856/62687123-ad2dd200-b9f8-11e9-97b9-91c98a566b01.png)
`lib.wx.component.d.ts`

![image](https://user-images.githubusercontent.com/5133856/62687202-dea69d80-b9f8-11e9-9925-6370696c2984.png)
![image](https://user-images.githubusercontent.com/5133856/62687218-e9613280-b9f8-11e9-812b-dcd41e5c01e9.png)
`lib.wx.page.d.ts`

**Comment by wechat-miniprogram-admin** [comment]
如注释所说：
> `key` 可以以数据路径的形式给出，支持改变数组中的某一项或对象的某个属性，如 `array[2].message`，`a.b.c.d`，并且不需要在 `this.data` 中预先定义。

而且即使不考虑数据路径，`setData` 本身也支持设置未在 `this.data` 中预先定义的属性。这里的 `IAnyObject` 是基于这些考虑给出的，可以参考一下

**Comment by NewFuture** [comment]
保留泛型还是有必要的。
ts的重要作用就是进行类型检查和类型提示

这个fork版本有兼顾折中的方案
https://github.com/MS-DG/api-typings/blob/master/types/wx/lib.wx.page.d.ts#L115-L125
```ts
    setData(
      /** 这次要改变的数据
       *
       * 以 `key: value` 的形式表示，将 `this.data` 中的 `key` 对应的值改变成 `value`。
       *
       * 其中 `key` 可以以数据路径的形式给出，支持改变数组中的某一项或对象的某个属性，如 `array[2].message`，`a.b.c.d`，并且不需要在 this.data 中预先定义。
       */
      data: Partial<D> & Record<string, NonUndefined<any>>,
      /** setData引起的界面更新渲染完毕后的回调函数，最低基础库： `1.5.0` */
      callback?: () => void
    ): void;
```

如果setData的字段在data中则进行类型检查，不在则不限制。
同时在setData({}) 输入时也会有自动提示。

**Comment by loveholly** [comment]
@NewFuture 准备用你们的库了 😄

**Comment by wechat-miniprogram-admin** [comment]
`data: Partial<D> & Record<string, NonUndefined<any>>`
这个方案挺好，那么下一个版本就改成这样吧
