### ISSUE TITLE
文档中添加这个库的建议

### ISSUE THREAD

**Issue by GodofHope** [wechat-miniprogram/api-typings#56]
文档中原文只有：

---
### TypeScript 支持

如果项目需要使用 TypeScript 语言开发，开发者工具在创建项目选择快速启动模板时，提供了使用 TypeScript 语言的 QuickStart 项目，可以选择创建此项目并进行后续开发。

要构建并使用 TypeScript 项目，可能需要安装 npm。通过配置编译前的预置命令，可以实现在编译前运行 tsc 以将其编译到 js 文件。

如需配置 TypeScript 编译选项，请参考 tsconfig.json 的配置。

> 注：小程序仅支持运行 JS 文件，因此所有的 TS 文件都默认不会被打包上传。

---

希望能放上这个库链接，我一直用的就是开发者工具给我生成的那套tying，这几天才发现了这个库的。

**Comment by wechat-miniprogram-admin** [comment]
工具目前的定义文件就是这个 repo 的旧版本，之后工具会同步拉取对应基础库的最新版本的定义文件，感谢你的建议。

**Comment by IceApriler** [comment]
@wechat-miniprogram-admin 

最好还是让开发者使用npm的方式引入typings，这样可以及时获得更新。因为工具中的typings只能保证创建项目时是最新的，后续是无法得到官方升级维护的，只能手动更新。

**Comment by wechat-miniprogram-admin** [comment]
这个我们后续会尝试让工具能够自动更新定义的。

**Comment by GodofHope** [comment]
还是希望能在文档上加入这个库，不然用户可能都不知道到哪里提issue
