### ISSUE TITLE
是否有计划增加event.d.ts？

### ISSUE THREAD

**Issue by IceApriler** [wechat-miniprogram/api-typings#58]
类似于 https://github.com/MS-DG/api-typings/blob/master/types/wx/lib.event.d.ts

这个也挺重要的。

**Comment by wechat-miniprogram-admin** [comment]
感谢建议，我们沟通一下

**Comment by kchanlee** [comment]
同意楼主！希望能官方能把事件系统的类定义加进去！

**Comment by cat-walk** [comment]
我看到官方的源文件里，types/wx/lib.wx.event.d.ts这个文件有很多好的事件，比如BaseEvent、CustomEvent、SwiperChange之类的，但是最后导出（npm安装下来的依赖）却没有导出这些事件，希望能加上，否则开发者只能自己从源代码里复制，感觉很浪费时间。感谢！

**Comment by Mister-Hope** [comment]
> 我看到官方的源文件里，types/wx/lib.wx.event.d.ts这个文件有很多好的事件，比如BaseEvent、CustomEvent、SwiperChange之类的，但是最后导出（npm安装下来的依赖）却没有导出这些事件，希望能加上，否则开发者只能自己从源代码里复制，感觉很浪费时间。感谢！

那个事件是我补的，PR merge 之后官方好像还没发新版本。

**Comment by SgLy** [comment]
我们自己的 npm 包发了，`@types` 那边的因为要提 pr 给他们审核，所以同步得没那么勤快😂

**Comment by SgLy** [comment]
#151 中已经添加了一部分事件的定义了，如果有缺漏或者需要补充的再另外提 issue 处理吧
