### ISSUE TITLE
部分参数调整建议

### ISSUE THREAD

**Issue by Realgomu** [wechat-miniprogram/api-typings#6]
1 按照文档中 Animation Step 方法应返回 Animation，以支持链式调用，现在返回了 void
2 SelectorQuery 中 selectAll 方法缺少 selector  参数
3 Storage 相关方法只定义了基础 object 类型，应使用联合类型 object | string | boolean
4 canvasToTempFilePath 和 createCanvasContext 缺少在组件环境下的 component this 参数

**Comment by SgLy** [comment]
收到啦，会随下一版本基础库修复~
