### ISSUE TITLE
希望声明文件能够更规范

### ISSUE THREAD

**Issue by GodofHope** [wechat-miniprogram/api-typings#61]
希望该有的semi都有，而且不要出现`Array<string|number>`这种，而是`(string|number)[]`

**Comment by wechat-miniprogram-admin** [comment]
你举的例子是跟随 [`"array-type": [true, "array-simple"]`](https://palantir.github.io/tslint/rules/array-type/) 的

**Comment by GodofHope** [comment]
我举得这些都是符合`plugin:@typescript-eslint/recoremmended`的，目前tslint已经走向deprecated ，我觉得有必要符合新的parser recoremmended标准

**Comment by GodofHope** [comment]
毕竟有些人比如我可能会把声明文件拿出来放在项目目录文件夹里

**Comment by wechat-miniprogram-admin** [comment]
`array-type` 这条是目前 [dtslint](https://github.com/microsoft/dtslint) 建议的，即将添加上来的测试依赖于它。tslint 转向 eslint 这个问题我们有注意到，一些两者之间不同的标准之后我们会再讨论采用怎样的规范。

**Comment by NewFuture** [comment]
@GodofHope 拷到项目目录确实不是个好方法

另外:

`dtslint`不光是格式检查，还有类型推断测试, 专门用来lint和测试`.d.ts`的。
这个是 tslint和eslint 都做不了事情

**Comment by GodofHope** [comment]
我主要是需要对某些接口拿来做二次加工，所以就直接拿出来了

**Comment by GodofHope** [comment]
另外我现在还自己扩展了一些你的event事件，比如map组件的事件你就没有写。

**Comment by NewFuture** [comment]
@GodofHope  如果只是扩展的话 ，声明相同的 namespace 或者 interface 在本地文件里 ,
typescript 会在自动 merge 相同的 declaration,
复制文件的方案更新代价大(特别是这种还不稳定状态)

PS: 既然都加上怎么不PR一下 😃

**Comment by GodofHope** [comment]
I am not finished yet.

**Comment by GodofHope** [comment]
hhh习惯打了英文，我还没做完呢，而且我有一些api因为没用到事件也没写。等我忙完我小程序的可能会抽空好好写一下给你提个ＰＲ。毕竟各种杂七杂八的事件还真的不少。

**Comment by wechat-miniprogram-admin** [comment]
那么这个 issue 就先关闭了
