### ISSUE TITLE
Compoenent.dts存在问题

### ISSUE THREAD

**Issue by GodofHope** [wechat-miniprogram/api-typings#62]
```ts
Compoenent({
  properties: { config: { type: Object } },
  methods: {
    doc() {
      if (['doc', 'docx', 'ppt', 'pptx', 'xls', 'xlsx', 'pdf'].includes(this.data.config.docType)) {
      ...(此处省略)
  },
  options: {
    addGlobalClass: true, // 兼容QQ
    styleIsolation: 'shared'
  }
});
```

提示：类型“{ doc(): void; }”上不存在属性“data”。

**Comment by GodofHope** [comment]
同样也无法访问`this.properties`,提示：类型“{ doc(): void; }”上不存在属性“properties”。

**Comment by wechat-miniprogram-admin** [comment]
除了 `styleIsolation` 还没加到定义里以外，如下代码的编译是通过的

```typescript
/// <reference path="./node_modules/miniprogram-api-typings/index.d.ts" />

Component({
  properties: { config: { type: Object } },
  methods: {
    doc() {
      this.data.config // $ExpectType object
    },
  },
  options: {
    addGlobalClass: true, // 兼容QQ
  },
})
```

编译选项是
```json
{
  "compilerOptions": {
    "target": "es5",
    "noImplicitAny": true,
    "strict": true,
  }
}
```

**Comment by GodofHope** [comment]
好的，我看看我这边的问题

**Comment by GodofHope** [comment]
我将`styleIsolation: 'shared'`注释掉一切就正常了，麻烦修复一下这个？

**Comment by GodofHope** [comment]
可别fix in next version 求您hhh，不用我新提一个issue吧

**Comment by wechat-miniprogram-admin** [comment]
👌

**Comment by NewFuture** [comment]
@wechat-miniprogram-admin 能否实现类似功能 https://github.com/MS-DG/api-typings/issues/11

虽然对于Component 参数来说是Object/Array (但是希望是Item/Item[])

但是在实际调用的时候是希望有具体的类型约束和推断

**Comment by GodofHope** [comment]
```ts

interface Config{
 ...
}

Compoenent({
  properties: { config: { type: Object } },
  methods: {
      a(){
        this.data.config.xxx
     }
   }
```

我还有一个问题,我现在定义了一个config的接口,我如何把它设置成config的类型呢呢?目前直接访问`this.data.config.xxx`会报错`类型“object”上不存在属性“xxx”。`

**Comment by wechat-miniprogram-admin** [comment]
现在 `properties` 类型为 `ObjectConstructor` 时给出的对应类型是 `object`，不过结合你这个例子，可能给 `Record<string, any>` 会比较好

**Comment by GodofHope** [comment]
目前好像没有一个类似隔壁[vue-function-api](https://github.com/vuejs/vue-function-api/issues/55)的方案能够convert

**Comment by GodofHope** [comment]
首先肯定是咱想个办法先解决报错的问题，然后最好给一个能够convert的例子，让开发者转换成自己定义的接口类型，最好不要让开发者每次访问的时候自己转换。

**Comment by GodofHope** [comment]
目前我暂时用的是`this.data.object as unknown as XXX`

**Comment by wechat-miniprogram-admin** [comment]
这个问题可能比较难解决，因为对应字段（指 `this.data.config`）的类型是从 `types` 的类型推导的。相同的 `types` 类型（比如 `ObjectConstructor`）肯定没办法推导出两种不同的类型；但如果放开 `types` 的类型限制，允许例如 `type: (Object as unknown) as () => Item` 这样的写法的话，会让 `type: ItemConstructor // $ExpectType () => Item` 也通过编译，这显然是有问题的。

这里我暂时没有想到太好的解决方法，不知道你们有没有什么方案？

**Comment by NewFuture** [comment]
这是采用VUE的解决方案
https://github.com/MS-DG/api-typings/blob/master/types/wx/lib.wx.component.d.ts#L3

```ts
interface Item {
    id: string;
    name: string;
}
Component({
    properties: {
        list: (Array as unknown) as () => Item[], // ()=>Item[] 定义一个item[]数组的构造器
        item: {
            type: (Object as unknown) as () => Item, // ()=>Item 定义 Item Object的构造器
            observer(newData: Item, oldData: Item) {
                if (newData && oldData && newData.id === oldData.id) {
                    return;
                }
            },
        },
    },
    methods: {
        doSth() {
            console.log(this.properties.item.id);
            console.log(this.properties.list[0]);
        },
    },
});
```
不够直观，但是没有发现更好的解决方案

**Comment by GodofHope** [comment]
呀，测试加进去了？

**Comment by wechat-miniprogram-admin** [comment]
后面关于 properties 类型的问题归到 #67 讨论吧
