### ISSUE TITLE
Page使用泛型后，this.data不能正常推导

### ISSUE THREAD

**Issue by IceApriler** [wechat-miniprogram/api-typings#63]
源代码
```ts
// logs.js
import { formatTime } from '../../utils/util'

type DataType = {
  /** 日志 */
  logs: string[]
}
type CustomOption = {
  /** 获取日志 */
  getLogs(): string[]
}


Page<DataType, CustomOption>({
  data: {
    logs: []
  },
  getLogs() {
    return (wx.getStorageSync('logs') || []).map((log: number) => {
      return formatTime(new Date(log))
    })
  },
  onLoad() {
    this.setData({
      logs: this.getLogs()
    })
    console.log(this.logs)
    console.log(this.data.logs)
  }
})
```

读取this.data提示类型“Instance<DataType, CustomOption>”上不存在属性“data”
![image](https://user-images.githubusercontent.com/29689307/63009562-5708d500-beb7-11e9-84d9-8882dff2e51a.png)

测试后，发现data中的数据被推导到page实例上了：
![image](https://user-images.githubusercontent.com/29689307/63009537-4c4e4000-beb7-11e9-863d-12b4e24c8d06.png)

**Comment by wechat-miniprogram-admin** [comment]
如下编译选项下无法复现，表现正常

```json
{
  "compilerOptions": {
    "target": "es5",
    "noImplicitAny": true,
    "strict": true,
  }
}
```

**Comment by IceApriler** [comment]
升级到2.8.0后就好使了，是2.7.7-1版本的问题~

**Comment by IceApriler** [comment]
升级后我发现IAnyObject没有全局暴露了，不能直接用，得通过WechatMiniprogram获取，🤣

**Comment by wechat-miniprogram-admin** [comment]
虽然 `IAnyObject` 还挺好使的，不过想了想也算污染了全局，就收回来了，也算是个 breaking change 😂

**Comment by IceApriler** [comment]
嗯嗯，有道理，IAnyObject这种还是写在自己源码里比较好。
