### ISSUE TITLE
关于wx.request()

### ISSUE THREAD

**Issue by w0330t** [wechat-miniprogram/api-typings#65]
在success里面直接调用返回的结果中的`result.data.errcode`会报一个错误

```
TS2339: Property 'errcode' does not exist on type 'string | object | ArrayBuffer'.
 Property 'errcode' does not exist on type 'string'.
```

请问这是不是BUG？

**Comment by wechat-miniprogram-admin** [comment]
算的，这里我们把 `object` 修成 `Record<string, any>` 吧

**Comment by wechat-miniprogram-admin** [comment]
在 2.8.0-2 中修复了，具体处理方法可以参考 https://github.com/wechat-miniprogram/api-typings/blob/master/test/issue.test.ts#L129-L146

**Comment by JoshuaPoddoku** [comment]
![Screenshot (48)](https://user-images.githubusercontent.com/31725457/70604917-7f170380-1c1f-11ea-8491-cdaf23f373f6.png)
Please help me

**Comment by longma19900415** [comment]
I have an answer to JoshuaPoddoku's question.
In case you use your own domain(web server) with some backend-Rest Apis, you should register your domains and there are some materials on how to register them on Internet.
But there is another option for using your own server.
I suppose you write your code using WeChat Devtools.
Go to 'Settings' > 'Project Settings' and in 'Local Settings' and check 'Does not verify valid domain names, ....'.
After that, you should be able to use your own server and if you have some backend and Rest APis running on the server, you will be able to get or set data from the server.
If you are developing a wechat miniprogram, this is a good option but it is not recommended in production mode.
I hope this answers your question
