### ISSUE TITLE
Bug:muti type define for console

### ISSUE THREAD

**Issue by GodofHope** [wechat-miniprogram/api-typings#66]
wx.api.d.ts line14566:
```ts
declare const console: WechatMiniprogram.Console
```

which will cause an error:

```
Cannot redeclare block-scoped variable 'console'
```

since console is already define in `node_modules/typescript/lib/lib.dom.d.ts` line 17510:

```ts
declare var console: Console;
```

**Comment by GodofHope** [comment]
我忘了，我还打的英文hhhh ，280-2版本新增的这行建议去掉，不然编译报错呀

**Comment by NewFuture** [comment]
@GodofHope  这个其实最好去掉 `lib.dom` 依赖，而不是改微信的typing，小程序里面用不了dom里的内容

**Comment by IceApriler** [comment]
我也遇到这个问题了，`"lib": ["es6"]`这样声明试了试，好像不能移除dom依赖。

**Comment by John0King** [comment]
@IceApriler  改完 这个配置文件， 重启一下 vs code , 并且留意一下你用的第三方包， 如果里面 手动
`///<reference lib="dom" />` 了， 那你 就只能改他的文件了

**Comment by IceApriler** [comment]
找到原因了，问题出在我编译工具和项目共用一份`tsconfig`，工具用了`node`包，和`wx`的`console`冲突了。

理论上应该编译工具和项目各一份`tsconfig`，不过也可以`"skipLibCheck": true`来解决。

**Comment by wechat-miniprogram-admin** [comment]
目前定义文件都是逻辑侧的定义，逻辑侧这边没有 DOM 接口，`console` 其实是基础库提供的。与其说新加了进去，倒不如说是之前一直缺……这次补上之后就可以去掉 `lib.dom` 了。
（甚至还没回复就已经 close 了）

**Comment by huadong** [comment]
> declare const console: WechatMiniprogram.Console
declare const wx: WechatMiniprogram.Wx
declare function require(module: string): any
declare let module: { exports: any }
declare let exports: any

这里console, require, module, exports的定义，我觉得还是欠妥。
当把它引入到快平台框架中，比如kbone、uni-app之类，就需要用到dom的定义。而用webpack进行打包编译的话，require会冲突。

快平台框架冲突：console
webpack环境冲突：require

应该把这几个定义单列出来：
>declare const console: WechatMiniprogram.Console
declare function require(module: string): any
declare let module: { exports: any }
declare let exports: any

这样可以根据不同的环境引入，非常灵活。

**Comment by xmsz** [comment]
这个问题 确实很蛋疼
还有一个场景

我要打包一些工具包，工具包里不仅仅有专属小程序的

结果打包的时候就冲突了...

所以我支持不应该去定义console这类，可以让开发者自己添加

**Comment by John0King** [comment]
@xmsz
冲突总是会存在，
   ts.config 有个配置，可以关掉定义文件错误  "skipLibCheck:true"

**Comment by xmsz** [comment]
> @xmsz
> 冲突总是会存在，
> ts.config 有个配置，可以关掉定义文件错误 "skipLibCheck:true"

有点得不偿失，现在临时手动在包里注释掉代码

**Comment by Mister-Hope** [comment]
补一个我在开发框架遇到的问题

setTimeout 也会冲突，如果任何package引入了 node 定义文件

**Comment by redblue9771** [comment]
尝试引入ApolloClient结果在定义文件卡住，突然失去了用ts的意义

**Comment by yesvods** [comment]
一些包的维护，需要兼容多端：浏览器、小程序，除了注释本地代码有更好的解决方案吗
