### ISSUE TITLE
调用 behaviors 混入的方法，ts提示不存在，有什么好解决的方案吗

### ISSUE THREAD

**Issue by clevok** [wechat-miniprogram/api-typings#68]

**Comment by wechat-miniprogram-admin** [comment]
可以考虑一下用类似 [`computed.test.ts`](https://github.com/wechat-miniprogram/api-typings/blob/master/test/computed.test.ts#L1-L40) 的方法自己扩展定义

**Comment by clevok** [comment]
这样子呀，好吧。。。
