### ISSUE TITLE
Console 定义冲突

### ISSUE THREAD

**Issue by Mr-SPM** [wechat-miniprogram/api-typings#70]
tsc 报错
Cannot redeclare block-scoped variable 'console'.

![image](https://user-images.githubusercontent.com/25722226/64001402-4e143680-cb3a-11e9-9054-2fdf768bf305.png)

**Comment by John0King** [comment]
duplicate  to #66

**Comment by wechat-miniprogram-admin** [comment]
Duplicate of #66 . 建议检查一下编译选项中是否包含了 `lib: [ "dom" ]` 并移除

**Comment by CaicoLeung** [comment]
`lib: ["dom"]`没有包含, 还是会提示重复定义

**Comment by Mister-Hope** [comment]
> `lib: ["dom"]`没有包含, 还是会提示重复定义

可能是你使用了包含types node或者 dom的package
