### ISSUE TITLE
完善一些接口细节

### ISSUE THREAD

**Issue by Mister-Hope** [wechat-miniprogram/api-typings#71]
举一个例子：`GetSystemInfoSyncResult`

```ts
 2001:       platform: string
```

可以更加细致的改为

```ts
 2001:       platform: 'ios' | 'android' | 'windows' | 'unknown'
```

这样会有助于开发者，比如我最开始就不知道'ios'是小写，我就只能打一个log然后跑到各个机型上去尝试。

这些例子有好多，我随便再举一个：`wx.showToast`的`icon`

**Comment by wechat-miniprogram-admin** [comment]
这个的可选值我再去确认一下。很多已经稳定的接口的参数很难一个个排查，如果还有其他的也可以列一下，方便跟进

（本质上就是个文档问题，文档没有 issue 提到这里来了……）

**Comment by wechat-miniprogram-admin** [comment]
`wx.showToast` 的 `icon` 这不是有吗 https://github.com/wechat-miniprogram/api-typings/blob/master/types/wx/lib.wx.api.d.ts#L4041-L4047

**Comment by SgLy** [comment]
文档那边的 issue 或者 changelog 我们讨论一下看有没有好的解决方案吧，这个 issue 没有实际问题就先 close 了，还有问题的话再 reopen 或者开新的吧
