### ISSUE TITLE
[page] options的定义

### ISSUE THREAD

**Issue by NewFuture** [wechat-miniprogram/api-typings#72]
从v2.1.0之后 PageInstance 上存在`options`的属性

这个是否应该补上，

references:

https://github.com/MS-DG/api-typings/pull/24
https://github.com/MS-DG/api-typings/pull/25

**Comment by wechat-miniprogram-admin** [comment]
文档上没有的一些属性和方法是我们不推荐使用，也不保证可用的，因此就不添加到定义里去啦
