### ISSUE TITLE
一些细节错误

### ISSUE THREAD

**Issue by cnjack** [wechat-miniprogram/api-typings#73]
lib.wx.api.d.ts
SocketTaskOnErrorCallbackResult
应该定义为
```
interface WebScoketCloseCallbackResult {
    code: number;
    reason: string;
}
```

SocketTask
应该加上
```
readyState: SocketStatus;
```
并附上
```
enum SocketStatus {
    CONNECTING,
    OPEN,
    CLOSING,
    CLOSED
}
```

**Comment by wechat-miniprogram-admin** [comment]
这个 [文档](https://developers.weixin.qq.com/miniprogram/dev/api/network/websocket/SocketTask.close.html) 里也没有，我们确认一下。

**Comment by cnjack** [comment]
好的 我console打印了下看到的😜

**Comment by cnjack** [comment]
@wechat-miniprogram-admin 亲啥时候可以处理一下呀

**Comment by cnjack** [comment]
@wechat-miniprogram-admin @SgLy 如何了呀 我的一个库依赖这个issue呀 我现在在本地做了link 还是希望可以fix一下呀

**Comment by wechat-miniprogram-admin** [comment]
这边确认了一下，这个 `readyState` 没有在文档上是因为目前是内部使用，所以我们也不保证它正确以及长期可用的，因此就不加到定义里了。如果要使用的话可以像 [这样](https://github.com/wechat-miniprogram/api-typings/blob/master/test/api-extend.test.ts) 补充到自己的定义里，不过我们是不建议使用的～

**Comment by cnjack** [comment]
onclose 的 response? WebScoketCloseCallbackResult 这个文档是有问题的

**Comment by cnjack** [comment]
谢谢大佬~
