### ISSUE TITLE
蓝牙 onBluetoothDeviceFound 回调函数接口

### ISSUE THREAD

**Issue by clevok** [wechat-miniprogram/api-typings#75]
type OnBluetoothDeviceFoundCallback = (
        /** 新搜索到的设备列表 */
        devices: CallbackBlueToothDevice[],
    ) => void

事实上,应该还被包裹在一个对象中
type OnBluetoothDeviceFoundCallback = (
        /** 新搜索到的设备列表 */
        result: {devices: CallbackBlueToothDevice[]}
    ) => void

**Comment by wechat-miniprogram-admin** [comment]
感谢反馈，已经确认，下一个版本修复~
