### ISSUE TITLE
建议可以添加到tsconfig.lib中

### ISSUE THREAD

**Issue by cnjack** [wechat-miniprogram/api-typings#76]
如果可以添加到tsconfig的lib中,可以直接在tsconfig.json中直接添加lib了,这样就更为方便开发了,如果ts官方不接受可以考虑直接copy文件到typescript的文件中去,但是不知道是否有用

**Comment by cnjack** [comment]
vscode测试确认直接copy不可行.....

**Comment by wechat-miniprogram-admin** [comment]
`lib` 在 [这里](https://www.typescriptlang.org/docs/handbook/compiler-options.html) 有列举，暂时还没有听说有可以提交到 `lib` 的操作……

**Comment by GodofHope** [comment]
我也没听过这种操作。tslib是官方预设的一些固定的库，你这只是一个开发工具的类型定义库。全世界那么多用type script的人还要以后下一份这个？

**Comment by cnjack** [comment]
看来是不太可行了
