### ISSUE TITLE
Cannot redeclare block-scoped variable 'console'

### ISSUE THREAD

**Issue by JeKing** [wechat-miniprogram/api-typings#78]
![image](https://user-images.githubusercontent.com/478552/64941790-1a574180-d89a-11e9-9081-002a23eeabdc.png)
由于需要获取process.env的变量，所以装了@types/node，但是更新完2.8.2后，就报错了，这个要如何解决

**Comment by wechat-miniprogram-admin** [comment]
Duplicate of #66 ，小程序的 `tsconfig.json` 里通过指定 `lib` 来去掉其他依赖

**Comment by JeKing** [comment]
"lib": ["es6"] 
![image](https://user-images.githubusercontent.com/478552/64944280-9e142c80-d8a0-11e9-95ca-0c4d8f1e63f9.png)已经去掉了，但是还是会有问题

**Comment by NewFuture** [comment]
@JeKing 同时 引入了 node 的定义的问题，

如果是自动引入的配置就行了
```json
    "types": ["miniprogram-api-typings"],
```
参考 https://github.com/NewFuture/miniprogram-template/blob/master/tsconfig.json#L35

**Comment by John0King** [comment]
@NewFuture @JeKing  这个问题困扰我很久，也问过typescript团队， 出现问题的原因是:  微信有自己的console全局变量 (WechatConsole), 浏览器有自己的 console 全局变量(可以认为是DomConsole), node 也有自己的 console全局变量（NodeConsole）,  这个时候引用一些第三方的定义文件会造成无法编译的问题。（事实上全局变量只能有一个，虽然万幸的是，目前他们的函数签名一致。）

不过， 万幸的是， **typescript 里面提供了解决这种问题的选项，`--skipLibCheck`, 这个也可以指定到 tsconfig.js 里面**

**Comment by wechat-miniprogram-admin** [comment]
DOM 的 console 可以通过指定 lib 来去除（如 `"lib": ["es6"]`)。至于 Node 的 console，小程序和其他的 ts 代码（如服务端）属于不同的运行环境，最好是有各自独立的 tsconfig。小程序如果有自己的 node_modules，可以用 `"typeRoots": [ "./node_modules" ]` 来阻止 ts 向上查找外面的 node_modules 里的定义；如果没有自己的 node_modules，可以考虑 `"types": ["miniprogram-api-typings"]`。
