### ISSUE TITLE
canvas设置线条样式strokeStyle应该支持渐变类型

### ISSUE THREAD

**Issue by liziwork** [wechat-miniprogram/api-typings#79]
![image](https://user-images.githubusercontent.com/19724731/65008852-4677ce80-d93d-11e9-98a8-c04ffceb11cc.png)
![image](https://user-images.githubusercontent.com/19724731/65008881-5f807f80-d93d-11e9-866a-d21947c53d89.png)
给strokeStyle加上渐变类型则错误提示没了
strokeStyle: string | CanvasGradient

**Comment by wechat-miniprogram-admin** [comment]
收到，近期修复
