### ISSUE TITLE
未找到npm包入口文件

### ISSUE THREAD

**Issue by w0330t** [wechat-miniprogram/api-typings#81]
![image](https://user-images.githubusercontent.com/4970238/65258492-8d301900-db35-11e9-9613-dfa65c9a7706.png)
我把typing安装在了小程序的node_modules里面，然后在构建的时候就报这个错误，

虽然我也知道大概不应该把这个安装进去……

如果安装了，在构建的时候能否跳过这个module，比如typescript小程序IDE也没检查啊。

或者干脆手动扔typing文件夹里？每次更新就从本项目里面拖一次？

对了，还有如果安装了其实会发生[#78](https://github.com/wechat-miniprogram/api-typings/issues/78)的报错，虽然我加了skiplibcheck临时解决了这个问题。

npm的萌新请各位大神给个建议~谢谢。

**Comment by NewFuture** [comment]
装 devDependencies
```bash
npm install miniprogram-api-typings -D
```

TS 模板可以参考 https://github.com/NewFuture/miniprogram-template
自动npm install时自动去除 非直接依赖的 `@types`
