### ISSUE TITLE
一点关于MethodOption的建议

### ISSUE THREAD

**Issue by cnjack** [wechat-miniprogram/api-typings#82]
lib.wx.component.d.ts
```
type MethodOption = Record<string, (...args: any[]) => any>
```
修改成
```
type MethodOption = Record<string, ((...args: any[]) => any) | undefined>
```

我目前没法使用如下写法
```
interface IDialogMethod extends WechatMiniprogram.Component.MethodOption {
    func?: () => void;
}
```

**Comment by cnjack** [comment]
我外部需要依赖一个Component 但是对于Method有些是不需要的 是可选的, 但是现在没法实现这个需求

**Comment by SgLy** [comment]
能说一下具体是在什么情况下会有这种写法吗😂好像没有想到什么情况是需要这个可选的

**Comment by cnjack** [comment]
我现在写的是一个依赖于小程序component的一个jssdk(公司内部使用)
我依赖于一个component 所以我这边需要定义一下我的依赖,一些用于通知的接口不一定需要用户定义 但是是可选的,比如 断线通知是一个可选的func component选择实现sdk这边就调用 如果不实现则不调用
但是可选方法我也需要有一定的规范(对于传值和返回值) 所以需要这样的写法

**Comment by Mister-Hope** [comment]
我是没太明白你说的是啥。不过，调用之前判断一下方法是否存在不行么？

**Comment by Mister-Hope** [comment]
你的意思是，组件你不能控制，是另一个人来完成的，然后你负责组件的父组件/页面逻辑？然后你希望用ts给组件返回接口做一个规范？

**Comment by cnjack** [comment]
是的,组件是可以多种实现的,这个就是interface的作用啊 来定义抽象用

**Comment by cnjack** [comment]
我目前就是判断是否存在 但是这样可选函数我就没法给出定义了(需要通过文档的方式约束)

**Comment by cnjack** [comment]
@Mister-Hope  大佬如何了呀~

**Comment by SgLy** [comment]
emmm好像确实是不可避免，这个可选之后 2.9.0 带上吧

**Comment by cnjack** [comment]
好哒 谢谢大佬😆
