### ISSUE TITLE
TS不能调wx.postMessage

### ISSUE THREAD

**Issue by LaurenceSql** [wechat-miniprogram/api-typings#86]
已经从GITHUB上导入了.d.tsAPI接口，但是我看WX接口里并没有postMessage这个方法。使用JS可以直接wx.postMessage向开放数据域发送消息。TS怎么调呢？

**Comment by SgLy** [comment]
是小游戏的接口吗？这边好像没有在文档上看到相关接口的描述😂方便的话能不能给个链接

**Comment by LaurenceSql** [comment]
https://developers.weixin.qq.com/minigame/dev/api/open-api/context/OpenDataContext.html

**Comment by SgLy** [comment]
是小游戏的接口，这套定义不支持小游戏😂小游戏的定义还在计划中～

**Comment by LaurenceSql** [comment]
啊，好吧，谢谢大神！
