### ISSUE TITLE
关于break change版本的几个疑问，希望能帮忙解惑下，谢谢！

### ISSUE THREAD

**Issue by lihome** [wechat-miniprogram/api-typings#87]
1. 早期的typings版本中`lib.wa.es6.d.ts` 是存在`encodeURI`这些定义的，现在不见了
2.  `IAnyObject`被隐藏后，需要加`WechatMiniprogram.`前缀才能访问，新版本中命名空间名 `WechatMiniprogram`特别长，这样一个变量声明就差不多占一行。
 是说不建议开发者直接使用`IAnyObject`等命名空间的定义吗？

**Comment by SgLy** [comment]
1. 小程序环境和浏览器有一些区别，有些接口也是由基础库提供（例如 `console`），所以后面把这些接口都归纳到其他定义文件，删掉了 `es6` 这个文件。`encodeURI` 这些确实是有遗漏，我们清理一下补上
1. `IAnyObject` 毕竟不是一个标准的东西，可以算是一个缩写（对于 `Record<string, any>` 的），出于不污染开发者命名空间的考虑，就收进了小程序的命名空间里。如果你喜欢的话，可以在项目的定义文件里把它拉出来呀，比如 `type IAnyObject = WechatMiniprogram.IAnyObject` 这样

**Comment by lihome** [comment]
代码1：
```
wx.login({
  success(res): void {
    console.log(res.code)
  },
  fail(res): void {
    // TODO
  }
})
```
代码2：
```

wx.login({
  success(res: WechatMiniprogram.LoginSuccessCallbackResult): void {
    console.log(res.code)
  },
  fail(res: WechatMiniprogram.GeneralCallbackResult): void {
    // TODO
  }
})
```

以上两个代码片段中，代码1中的`res`确实能根据类型推断出里面会包含`code` 属性，但是个人还是偏向代码2的显示声明 `res`的类型参数，因为有后面的类型，看参数更清晰
主要是有如下的顾虑：

1. `WechatMiniprogram.`前缀太长，一个形参定义就的占用一行
2. `WechatMiniprogram`命名空间中的`LoginSuccessCallbackResult`可能在后续版本中更名
3. 有没有其他好的理由让我用`res`替换 `res: WechatMiniprogram.LoginSuccessCallbackResult`

**Comment by SgLy** [comment]
1. 对于前缀太长的问题，如果你喜欢，可以用 `import WX = WechatMiniprogram` 来 alias 命名空间，这个我稍后会加到测试里。多说一句关于命名空间长的原因，一是语义上比较清晰正式，二是防止和以后可能会有的其他类似定义冲突。
1. `LoginSuccessCallbackResult` 这个虽然是自动生成的，但目前工具链已经比较稳定了，虽然不能打百分之百的包票，但我们会尽量保证它轻易不会变动。有一种可能情况是新版本加了参数，例如从 `GeneralCallbackResult` 变化到了 `XxxxCallbackResult`，但我认为这种情况下编译不通过应该是比较合理的；
1. 这里把类型标注上……我认为属于个人喜好吧。不标注当然可以享受类型自动推导和少打字的好处，但我也没有特别的理由推荐你替换，这个看自己了？

**Comment by lihome** [comment]
好的，非常感谢解答！
