### ISSUE TITLE
CanvasToTempFilePathOption 存在问题

### ISSUE THREAD

**Issue by baranwang** [wechat-miniprogram/api-typings#88]
CanvasToTempFilePathOption 目前 `canvasId`、`canvas`、`quality` 均为必须属性，其实`canvasId`、`canvas`任选其一即可，而 `quality` 应为非必须属性吧

**Comment by patrickyyang** [comment]
同遇到这问题，只得吧canvas设置为''

**Comment by SgLy** [comment]
抱歉拖了很长时间，主要是文档那边现在暂时还不支持重载。`quality` 的问题下个版本会修复，重载可能要多等一个版本或者到下个版本的 patch😂
