### ISSUE TITLE
很奇怪的跳转问题

### ISSUE THREAD

**Issue by clevok** [wechat-miniprogram/api-typings#90]
```js
Component({
  properties: {
    done: Object
  },
  data: {
    done2: {}
  },
  methods: {
    async done () {
      // 无法正确的点击
      this.like();
      this.like2();
    },
    async like () {
      return this.properties;
    },
    async like2 () {
      return '123';
    }
  }
})
```
只要其中某个方法返回 data或者properties或者其中某个对象，vscode就无法正确的点击跳往到该方法
。。。。不知道是不是vscode的问题

![image](https://user-images.githubusercontent.com/22412954/70586288-9f37ca00-1c01-11ea-87f9-725ea4a61b3b.png)
![image](https://user-images.githubusercontent.com/22412954/70586302-a65ed800-1c01-11ea-8d5e-5f2ebe4fbb48.png)

**Comment by SgLy** [comment]
看起来包含 this.data 的那种情况下类型推导有些问题，我看一看

**Comment by SgLy** [comment]
补充一下这里，我看了下 vue 的 ts 文档，里面也有提到类似的 [涉及 `this` 的时候类型推导有问题的情况](https://cn.vuejs.org/v2/guide/typescript.html#%E6%A0%87%E6%B3%A8%E8%BF%94%E5%9B%9E%E5%80%BC)。这里面提到的给方法手动标注返回值的方法我试了一下，是有用的，如果短期内没有太好解决方法的话可以试一下

**Comment by SgLy** [comment]
最新的版本中用了 #161 的方法，这个问题应该是解决了，如果还不行的话再重新打开吧
