### ISSUE TITLE
No aggregate type in Database

### ISSUE THREAD

**Issue by CodingPapi** [wechat-miniprogram/api-typings#92]
Property 'aggregate' does not exist on type  'CollectionReference'.

**Comment by SgLy** [comment]
刚发的 2.10.3-1 更新了云开发的定义，试一下看看？

**Comment by Tian-Hun** [comment]
> 刚发的 2.10.3-1 更新了云开发的定义，试一下看看？
最新版本还是有这个问题。

**Comment by Tian-Hun** [comment]
> 刚发的 2.10.3-1 更新了云开发的定义，试一下看看？

最新版本还是有这个问题。

**Comment by arleyGuoLei** [comment]
2.12.0 和 v3 都有一样的问题，类型“CollectionReference”上不存在属性“aggregate”。ts(2339)
