### ISSUE TITLE
`tempImagePath` is missing in `TakePhotoSuccessCallbackResult`

### ISSUE THREAD

**Issue by malash** [wechat-miniprogram/api-typings#95]
# Why

To get the phone created by `CameraContext.takePhoto` we have to use `res.tempImagePath`.

For example, the [official demo](https://developers.weixin.qq.com/s/VBZ3Jim26zYu)  from [this page](https://developers.weixin.qq.com/miniprogram/dev/api/media/camera/CameraContext.html) used that API.

# What went wrong

After [this commit](https://github.com/wechat-miniprogram/api-typings/commit/1428227e24b5b51b26954c4716e386b64e623871#diff-2bc80e81787d294041b1b460b8c77b62L4692), it was removed.

![image](https://user-images.githubusercontent.com/1812118/71957508-e6c56c00-3228-11ea-90c7-e37066d205e4.png)

# How to fix it

1. Should re-add the `tempImagePath` to `TakePhotoSuccessCallbackResult`
2. Should also fix the document https://developers.weixin.qq.com/miniprogram/dev/api/media/camera/CameraContext.takePhoto.html
![image](https://user-images.githubusercontent.com/1812118/71958047-46704700-322a-11ea-8fa5-73fbcc34b6a1.png)

**Comment by SgLy** [comment]
Thanks a lot. Fixing it soon.

**Comment by SgLy** [comment]
fixed in 2.10.0-1
