### ISSUE TITLE
遗漏部分 Component 接口

### ISSUE THREAD

**Issue by SgLy** [wechat-miniprogram/api-typings#96]
> https://developers.weixin.qq.com/community/develop/doc/0002c208a4c4004fffb98eae156400

缺少 `selectOwnerComponent`, `animate` 及 `clearAnimation`

**Comment by todo-fixme** [comment]
BaseComponent 不支持 自定义的 bindtap='onComponentItemsClick' 方法传递参数？
methods：
{
onComponentItemsClick(e:any) {
      console.log("onDayClick", this);
    }
}

那 onComponentItemsClick 怎么接收参数？

**Comment by SgLy** [comment]
@todo-fixme 事件的类型现在还不支持，但我们有支持的计划，可以在 #58 跟踪。还有和这个 issue 无关的其他问题的话新开一个 issue 吧
